import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({channel:'msedge',headless:true});
const open=async page=>{await page.locator('#settings').click();await page.locator('#open-recordings').click();await page.locator('#record-backup').click();};
try{
 const source=await browser.newContext(),page=await source.newPage();await page.addInitScript(()=>{localStorage.setItem('reach-welcomed','1');navigator.mediaDevices.getUserMedia=async()=>{const a=new AudioContext(),o=a.createOscillator(),d=a.createMediaStreamDestination();o.connect(d);o.start();return d.stream;};});await page.goto('http://localhost:4173');await page.locator('#settings').click();await page.locator('#open-recordings').click();await page.locator('#record-phrase-yes').click();await page.locator('#record-start').click();await page.waitForTimeout(600);await page.locator('#record-stop').click();await page.waitForFunction(()=>!document.querySelector('#record-preview').disabled);await page.locator('#record-preview').click();await page.locator('#record-save').click();await page.waitForFunction(()=>document.querySelector('#recording-status').textContent.includes('saved'));await page.locator('#record-done').click();await open(page);const downloading=page.waitForEvent('download');await page.locator('#audio-export').click();const file=await downloading,original=JSON.parse(await readFile(await file.path(),'utf8'));assert.equal(original.recordings.length,1);const modified={...original,recordings:[...original.recordings,{...original.recordings[0],phrase:'no',text:'Mismatched words'}]};
 const target=await browser.newContext({viewport:{width:390,height:844}}),p=await target.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('reach-welcomed','1'));await p.goto('http://localhost:4173');await p.locator('#settings').click();await p.locator('#open-people').click();await p.locator('#person-name').fill('New device person');await p.locator('#person-create').click();await p.locator('#quick-done').click();await open(p);const upload=async value=>p.locator('#audio-import').setInputFiles({name:'recordings.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});await upload(modified);await p.waitForFunction(()=>document.querySelector('#audio-match-summary')?.textContent.includes('1 / 2'));assert.equal(await p.locator('#audio-replace').getAttribute('aria-pressed'),'false');
 assert.deepEqual((await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id),[]);await p.screenshot({path:'artifacts/audio-backup-preview.png'});await p.locator('#audio-apply').click();await p.waitForFunction(()=>document.querySelector('#audio-backup-status').textContent.includes('imported: 1'));await upload(original);await p.waitForFunction(()=>!!document.querySelector('#audio-apply'));assert.equal(await p.locator('#audio-apply').isDisabled(),true);await p.locator('#audio-replace').click();assert.equal(await p.locator('#audio-apply').isEnabled(),true);await p.locator('#audio-apply').click();await p.waitForFunction(()=>document.querySelector('#audio-backup-status').textContent.includes('imported: 1'));await upload({...original,recordings:[{...original.recordings[0],data:'INVALID!'}]});await p.waitForFunction(()=>document.querySelector('#audio-backup-status').textContent.includes('invalid recording'));assert.equal(await p.locator('#audio-apply').count(),0);
 await upload({...original,recordings:[{...original.recordings[0],data:'AQID'},{...original.recordings[0],phrase:'no',text:'No'}]});await p.waitForFunction(()=>!!document.querySelector('#audio-replace'));await p.locator('#audio-replace').click();await p.evaluate(()=>{window.originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,...args){if(this.name==='clips'&&value.phrase==='no')throw new DOMException('Simulated storage failure','QuotaExceededError');return originalPut.call(this,value,...args);};});await p.locator('#audio-apply').click();await p.waitForFunction(()=>document.querySelector('#audio-backup-status').textContent.includes('Simulated storage failure'));await p.evaluate(()=>IDBObjectStore.prototype.put=originalPut);
 const stored=await p.evaluate(()=>new Promise((resolve,reject)=>{const req=indexedDB.open('reach-recordings');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const get=req.result.transaction('clips').objectStore('clips').getAll();get.onsuccess=()=>resolve(get.result.map(c=>({phrase:c.phrase,size:c.blob.size})));};}));assert.deepEqual(stored,[{phrase:'yes',size:Buffer.from(original.recordings[0].data,'base64').length}]);
 await p.locator('#audio-backup-done').click();await p.locator('[data-phrase=yes]').click();assert.ok((await p.locator('#speech-status').textContent()).includes('Saved recording'));await target.setOffline(true);await p.reload();await p.waitForTimeout(150);await p.locator('[data-phrase=yes]').click();assert.ok((await p.locator('#speech-status').textContent()).includes('Saved recording'));assert.deepEqual(errors,[]);console.log('PASS recorded-audio transfer, exact-match preview, unmatched exclusion, existing preservation, deliberate replacement, malformed rejection, transaction rollback after a staged write, accessibility and offline playback');
}finally{await browser.close();}
