import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {loadBoard} from '@shayc/open-board-format';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext(),page=await context.newPage();await page.addInitScript(()=>{localStorage.setItem('reach-settings',JSON.stringify({phrases:[{id:'custom-export',en:'My special message',sourceLanguage:'en',icon:'Heart'}],packs:{homeCare:['yes','no','custom-export',null,'water']}}));});
 await page.goto('http://localhost:4173');await page.locator('#welcome-touch').click();await page.locator('#settings').click();await page.locator('#open-board-export').click();assert.equal(await page.locator('#obf-preview li').count(),5);
 let exportNumber=0;const download=async()=>{const event=page.waitForEvent('download');await page.locator('#obf-download').click();const file=await event;await file.saveAs(`artifacts/reach-interop-${++exportNumber}.obf`);return (await loadBoard(await readFile(await file.path()))).board;};
 const board=await download();assert.deepEqual(board.grid.order,[['button-0','button-1','button-2'],[null,'button-3',null]]);assert.equal(board.buttons[2].label,'My special message');assert.ok(board.images.length);assert.ok(board.images.every(i=>i.content_type==='image/png'&&i.ext_reach_license_text.includes('ISC License')));assert.equal(board.sounds.length,0);
 const dimensions=await page.evaluate(async data=>{const image=new Image();image.src=data;await image.decode();return [image.naturalWidth,image.naturalHeight];},board.images[0].data);assert.deepEqual(dimensions,[160,160]);
 const audioData=await page.evaluate(async()=>{
  const person=JSON.parse(localStorage.getItem('reach-profiles-v1')).activeId,bytes=new Uint8Array(46),view=new DataView(bytes.buffer);const text=(offset,s)=>[...s].forEach((c,i)=>bytes[offset+i]=c.charCodeAt(0));text(0,'RIFF');view.setUint32(4,38,true);text(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,8000,true);view.setUint32(28,16000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,2,true);
  const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('reach-recordings',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});await new Promise((resolve,reject)=>{const tx=db.transaction('clips','readwrite'),store=tx.objectStore('clips');for(const [owner,phrase,message] of [[person,'yes','Yes'],[person,'no','Stale text'],['different-person','water','Please give me water']])store.put({id:JSON.stringify([owner,phrase,'en']),person:owner,phrase,language:'en',text:message,blob:new Blob([bytes],{type:'audio/wav'})});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();return btoa(String.fromCharCode(...bytes));
 });await page.locator('#obf-audio').click();const withAudio=await download();assert.equal(withAudio.sounds.length,1);assert.equal(withAudio.sounds[0].data,'data:audio/wav;base64,'+audioData);assert.equal(withAudio.buttons[0].sound_id,withAudio.sounds[0].id);assert.equal(withAudio.buttons[1].sound_id,undefined);
 await page.locator('#obf-language-zh').click();assert.equal(await page.locator('#obf-download').isDisabled(),true);await page.locator('#obf-allow-missing').click();await page.locator('#obf-columns-2').click();const zh=await download();assert.equal(zh.locale,'zh');assert.equal(zh.grid.order[1][0],null);assert.deepEqual(zh.ext_reach_export.missingPositions,[3]);assert.equal(zh.buttons[0].label,'是');
 await page.setViewportSize({width:390,height:844});assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id),[]);await page.screenshot({path:'artifacts/open-board-export.png'});
 console.log('PASS independent OBF parsing, stable empty slots, embedded PNG decoding/attribution, missing-translation consent, column/language selection and narrow accessibility');
 let lateDownload=false;page.on('download',()=>lateDownload=true);await page.evaluate(()=>{const original=HTMLImageElement.prototype.decode;HTMLImageElement.prototype.decode=async function(){await new Promise(r=>setTimeout(r,300));return original.call(this);};});await page.locator('#obf-download').click();await page.locator('#obf-close').click();await page.waitForTimeout(2000);assert.equal(lateDownload,false);console.log('PASS matching audio only, current-person isolation and cancel during preparation');
}finally{await browser.close();}

