import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import {writeFile,mkdir} from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['camera']});
await context.addInitScript(()=>{
  // Deterministic moving canvas: exercise the video pipeline without a physical webcam.
  navigator.mediaDevices.getUserMedia=async()=>{
    const c=document.createElement('canvas');c.width=640;c.height=480;const ctx=c.getContext('2d');let x=0;
    const draw=()=>{ctx.fillStyle='#444';ctx.fillRect(0,0,640,480);ctx.fillStyle='#aaa';ctx.fillRect((x++%600),20,20,20);};draw();
    const timer=setInterval(draw,50);const stream=c.captureStream(20);const track=stream.getVideoTracks()[0];const stop=track.stop.bind(track);track.stop=()=>{clearInterval(timer);stop();};return stream;
  };
});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const results=[];
async function check(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS '+name);}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL '+name+': '+e.message);if(await page.locator('#modal').evaluate(e=>e.open))await page.keyboard.press('Escape');}}
await page.goto('http://localhost:4173');
await check('first-run onboarding',async()=>{await page.locator('#modal').waitFor({state:'visible'});await page.locator('#welcome-touch').click();assert.equal(await page.locator('.tile').count(),6);});
await check('communication, repeat and clear',async()=>{await page.locator('[data-phrase="yes"]').click();assert.equal(await page.locator('#message').innerText(),'Yes');assert.equal(await page.locator('#repeat').isEnabled(),true);await page.locator('#repeat').click();await page.locator('#clear').click();assert.equal(await page.locator('#repeat').isEnabled(),false);});
await check('all icons rendered',async()=>{assert.equal(await page.locator('i[data-lucide]').count(),0);assert.equal(await page.locator('.tile-icon svg').count(),6);});
await check('language and settings persist',async()=>{await page.locator('#language').click();await page.locator('[data-lang=th]').click();await page.locator('#quick-done').click();await page.locator('[data-phrase="yes"]').click();assert.equal(await page.locator('#message').innerText(),'ใช่');await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'th');await page.locator('#language').click();await page.locator('[data-lang=en]').click();await page.locator('#quick-done').click();});
await check('personal phrases escape HTML and persist',async()=>{await page.locator('#board-topics').click();await page.locator('#modal [data-category="mine"]').click();await page.locator('#add-first').click();await page.locator('#phrase-en').fill('Hello <friend>');await page.locator('#phrase-th').fill('สวัสดี');await page.locator('#phrase-form button').click();await page.locator('#phrases-done').click();await page.locator('.tile').click();assert.equal(await page.locator('#message').innerText(),'Hello <friend>');await page.reload();await page.locator('#board-topics').click();await page.locator('#modal [data-category="mine"]').click();assert.equal(await page.locator('.tile-label').innerText(),'Hello <friend>');});
await check('dwell selects once and releases on pointer exit',async()=>{await page.locator('#dock-home').click();await page.locator('#change-input').click();await page.locator('[name="mode"][value="dwell"]').check();await page.locator('#dwell-time').fill('600');await page.locator('#input-done').click();await page.locator('[data-phrase="no"]').hover();await page.waitForTimeout(850);assert.equal(await page.locator('#message').innerText(),'No');await page.mouse.move(0,0);assert.equal(await page.locator('.dwelling').count(),0);});
await check('switch scanning selects and ignores held-key repeat',async()=>{await page.locator('#change-input').click();await page.locator('[name="mode"][value="switch"]').check();await page.locator('#input-done').click();await page.locator('#scan-start').click();await page.keyboard.press('Space');assert.equal(await page.locator('#message').innerText(),'Yes');await page.keyboard.down('Space');await page.keyboard.down('Space');await page.keyboard.up('Space');assert.equal(await page.locator('#message').innerText(),'Yes');await page.locator('#scan-start').click();});
await check('simplified layout and contrast settings',async()=>{await page.locator('#settings').click();await page.locator('#quick-advanced').click();await page.locator('#setting-layout').selectOption('simple');await page.locator('#setting-contrast').check();await page.locator('#settings-done').click();assert.equal(await page.locator('.tile').count(),4);assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('high-contrast')),true);await page.locator('#settings').click();await page.locator('#quick-advanced').click();await page.locator('#setting-layout').selectOption('full');await page.locator('#setting-contrast').uncheck();await page.locator('#settings-done').click();});
await check('camera starts with synthetic video and releases on pause',async()=>{await page.locator('#change-input').click();await page.locator('[name="mode"][value="motion"]').check();await page.locator('#camera-start').click();await page.waitForFunction(()=>document.querySelector('#camera-preview video')?.readyState>=2);await page.locator('#calibrate').click();await page.waitForTimeout(3400);assert.match(await page.locator('#camera-status').innerText(),/calibrated/);await page.locator('#input-done').click();await page.locator('#pause').click();await page.locator('#resume').click();await page.locator('#change-input').click();assert.equal(await page.locator('#camera-preview video').count(),0);await page.locator('[name="mode"][value="touch"]').check();await page.locator('#input-done').click();});
await check('hand model initializes, no hand means no selection',async()=>{await page.locator('#change-input').click();await page.locator('[name="mode"][value="hand"]').check();await page.locator('#camera-start').click();await page.waitForFunction(()=>document.querySelector('#camera-status')?.textContent.includes('resting position'),{},{timeout:60000});await page.locator('#calibrate').click();assert.match(await page.locator('#camera-status').innerText(),/No hand/);await page.locator('#camera-stop').click();await page.locator('[name="mode"][value="touch"]').check();await page.locator('#input-done').click();});
await check('no accessibility rule violations on board',async()=>{const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();await writeFile('artifacts/accessibility.json',JSON.stringify(a.violations,null,2));assert.deepEqual(a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);});
await check('responsive layouts and screenshots',async()=>{for(const [name,width,height] of [['desktop',1440,1000],['tablet',820,1180],['phone',390,844],['small-phone',320,740]]){await page.setViewportSize({width,height});await page.screenshot({path:`artifacts/${name}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,name+' overflow');const small=await page.locator('.tile').evaluateAll(els=>els.some(e=>e.clientWidth<44||e.clientHeight<44));assert.equal(small,false);}});
await check('offline reload retains board and phrases',async()=>{await page.waitForFunction(()=>document.querySelector('#offline-status').textContent.includes('Saved'));await context.setOffline(true);await page.reload();await page.locator('[data-phrase="yes"]').click();assert.equal(await page.locator('#message').innerText(),'Yes');await page.locator('#board-topics').click();await page.locator('#modal [data-category="mine"]').click();assert.equal(await page.locator('.tile-label').innerText(),'Hello <friend>');await context.setOffline(false);});
await check('no uncaught runtime errors',async()=>assert.deepEqual(errors,[]));
await writeFile('artifacts/browser-results.json',JSON.stringify(results,null,2));await browser.close();
if(results.some(r=>!r.pass))process.exitCode=1;

