import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('reach-welcomed','1');window.audioLog=[];window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>['en-US','ar','th','zh','hi','es'].map(lang=>({lang,localService:true})),cancel:()=>{},speak:u=>audioLog.push({text:u.text,lang:u.lang}),addEventListener:()=>{}}});});
 await page.goto('http://localhost:4173');const open=async()=>{await page.locator('#board-topics').click();await page.locator('#describe-care').click();};await open();
 for(const id of ['pain','shoulder','left','skip','today'])await page.locator('#care-'+id).click();
 assert.equal(await page.locator('#care-review').textContent(),'I have pain.\nLocation: Shoulder\nSide: Left\nWhen it started: Earlier today');assert.equal(await page.evaluate(()=>audioLog.length),0);
 await page.locator('#care-edit-side').click();await page.locator('#care-right').click();assert.ok((await page.locator('#care-review').textContent()).includes('Side: Right'));await page.locator('#care-speak').click();assert.equal(await page.evaluate(()=>audioLog.length),1);assert.equal(await page.locator('#message').textContent(),await page.locator('#care-review').textContent());
 await page.locator('#care-close').click();await open();assert.ok((await page.locator('#care-review').textContent()).includes('Side: Right'));
 await page.locator('#care-edit-location').click();await page.locator('#care-next').click();await page.locator('#care-next').click();await page.locator('#care-everywhere').click();assert.equal(await page.locator('#care-edit-side').count(),0);assert.equal((await page.locator('#care-review').textContent()).includes('Side:'),false);
 await page.locator('#care-close').click();await page.locator('#language').click();await page.locator('[data-lang=ar]').click();await page.locator('#quick-done').click();await open();assert.equal(await page.locator('#care-review').getAttribute('lang'),'ar');await page.locator('#care-speak').click();assert.equal(await page.evaluate(()=>audioLog.at(-1).lang),'ar');
 assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id),[]);await page.screenshot({path:'artifacts/care-review-arabic.png'});
 await page.locator('#care-restart').click();assert.equal(await page.locator('#care-review').count(),0);await page.locator('#care-close').click();await page.locator('#language').click();await page.locator('[data-lang=en]').click();await page.locator('#quick-done').click();
 await page.locator('#change-input').click();await page.locator('[value=dwell]').check();await page.locator('#dwell-time').fill('600');await page.locator('#input-done').click();await open();await page.mouse.move(0,0);await page.locator('#care-pain').hover();await page.waitForTimeout(1800);assert.ok((await page.locator('#care-step').textContent()).includes('Location'));assert.equal(await page.locator('#care-review').count(),0);await page.mouse.move(0,0);
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 await page.locator('#care-close').click();await page.locator('#change-input').click();await page.locator('[value=switch]').check();await page.locator('#scan-time').fill('1000');await page.locator('#input-done').click();await page.locator('#scan-start').click();await open();
 const spoken=await page.evaluate(()=>audioLog.length);await page.waitForFunction(()=>document.querySelector('#care-neck')?.classList.contains('scanning'),{},{timeout:15000});await page.keyboard.press('Space');assert.ok((await page.locator('#care-step').textContent()).includes('Side'));assert.equal(await page.evaluate(()=>audioLog.length),spoken);
 await page.reload();await open();assert.ok((await page.locator('#care-step').textContent()).includes('What do you feel?'));assert.deepEqual(errors,[]);console.log('PASS explicit care choices, correction, speech gate, all-over invariants, session-only draft, Arabic accessibility, dwell release, switch selection and widths');
}finally{await browser.close();}
