import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('reach-welcomed','1');window.audioLog=[];window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>['en-US','ar','th','zh','hi','es'].map(lang=>({lang,localService:true})),cancel:()=>audioLog.push({type:'cancel'}),speak:u=>audioLog.push({type:'speak',text:u.text,lang:u.lang}),addEventListener:()=>{}}});});
 await page.goto('http://localhost:4173');await page.locator('#write-message').click();await page.locator('[data-compose-phrase=yes]').click();await page.locator('[data-compose-phrase=no]').click();assert.equal(await page.locator('#compose-text').inputValue(),'Yes No');assert.equal(await page.evaluate(()=>audioLog.filter(e=>e.type==='speak').length),0);
 await page.locator('#compose-clear').click();await page.locator('#compose-letters').click();await page.locator('#compose-choice-0').click();for(const i of [0,1,2])await page.locator('#compose-choice-'+i).click();assert.equal(await page.locator('#compose-text').inputValue(),'abc');await page.locator('#compose-delete').click();assert.equal(await page.locator('#compose-text').inputValue(),'ab');await page.locator('#compose-undo').click();assert.equal(await page.locator('#compose-text').inputValue(),'abc');
 await page.locator('#compose-speak').click();assert.deepEqual(await page.evaluate(()=>audioLog.filter(e=>e.type==='speak').at(-1)),{type:'speak',text:'abc',lang:'en-US'});await page.locator('#compose-stop').click();assert.equal(await page.evaluate(()=>audioLog.at(-1).type),'cancel');
 await page.reload();await page.locator('#write-message').click();assert.equal(await page.locator('#compose-text').inputValue(),'abc');await page.locator('#compose-clear').click();await page.locator('#compose-close').click();console.log('PASS phrase/letter composition, undo, explicit speech/stop and draft reload');
 await page.locator('#language').click();await page.locator('[data-lang=ar]').click();await page.locator('#quick-done').click();await page.locator('#write-message').click();await page.locator('#compose-text').fill('أحبك');await page.locator('#compose-save').click();await page.locator('#compose-save').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('reach-settings')).phrases.length),1);
 const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(audit.violations.map(v=>v.id),[]);await page.screenshot({path:'artifacts/message-composer-arabic.png'});
 await page.locator('#compose-close').click();await page.locator('#language').click();await page.locator('[data-lang=en]').click();await page.locator('#quick-done').click();await page.locator('#board-topics').click();await page.locator('#modal [data-category=mine]').click();await page.locator('#board .tile').click();assert.equal(await page.evaluate(()=>audioLog.filter(e=>e.type==='speak').at(-1).lang),'ar');console.log('PASS native-language save, duplicate prevention and correct voice after UI language change');
 await page.locator('#change-input').click();await page.locator('[value=dwell]').check();await page.locator('#dwell-time').fill('600');await page.locator('#input-done').click();await page.locator('#write-message').click();await page.locator('#compose-clear').click();await page.locator('#compose-phrases').click();await page.mouse.move(0,0);await page.locator('#compose-choice-0').hover();await page.waitForTimeout(1700);assert.equal(await page.locator('#compose-text').inputValue(),'نعم');await page.mouse.move(0,0);assert.deepEqual(errors,[]);console.log('PASS dwell adds a phrase once per hover');
}finally{await browser.close();}
