import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import AxeBuilder from '@axe-core/playwright';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext();
await context.addInitScript(()=>{navigator.mediaDevices.getUserMedia=async()=>{const c=document.createElement('canvas');c.width=640;c.height=480;const ctx=c.getContext('2d');let n=0;const timer=setInterval(()=>{ctx.fillStyle='#444';ctx.fillRect(0,0,640,480);ctx.fillStyle='white';ctx.fillRect(n++%640,10,4,4);},30);const s=c.captureStream(30),t=s.getVideoTracks()[0],stop=t.stop.bind(t);t.stop=()=>{clearInterval(timer);stop();};return s;};});
const page=await context.newPage(),external=[],errors=[];page.on('request',r=>{if(!r.url().startsWith('http://localhost:4173')&&!r.url().startsWith('blob:'))external.push(r.url());});page.on('pageerror',e=>errors.push(e.message));
async function start(){await page.locator('#change-input').click();await page.locator('[value="eye"]').check();await page.locator('#eye-start').click();await page.waitForFunction(()=>document.querySelector('#eye-begin')?.disabled===false,{},{timeout:60000});}
await page.goto('http://localhost:4173');await page.locator('#welcome-touch').click();await start();await page.locator('#eye-begin').click();await page.waitForFunction(()=>document.querySelector('#eye-progress').textContent.includes('not clearly visible'));assert.equal(await page.locator('#eye-use').isVisible(),false);console.log('PASS real local face model loads, blank video cannot activate gaze');await page.locator('#eye-exit').click();
await context.setOffline(true);await page.reload();await start();console.log('PASS cached face model and runtime initialize offline');await page.locator('#eye-exit').click();await context.setOffline(false);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/eye-phone.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(audit.violations.map(v=>v.id),[]);console.log('PASS phone board layout and accessibility audit');assert.deepEqual(external,[]);assert.deepEqual(errors,[]);console.log('PASS no external requests or uncaught errors');await writeFile('artifacts/eye-runtime-results.json',JSON.stringify({passed:4,video:'Generated blank video; actual MediaPipe model loaded, no physical-person test'},null,2));await browser.close();
