import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});
await context.addInitScript(()=>{
 window.gazeTarget=[.5,.5];window.eyeClosed=false;window.freezeGaze=false;
 navigator.mediaDevices.getUserMedia=async()=>{const c=document.createElement('canvas');c.width=640;c.height=480;const ctx=c.getContext('2d');let n=0;const timer=setInterval(()=>{ctx.fillStyle='#444';ctx.fillRect(0,0,640,480);ctx.fillStyle='white';ctx.fillRect(n++%640,10,4,4);},30);const stream=c.captureStream(30);const track=stream.getVideoTracks()[0],stop=track.stop.bind(track);track.stop=()=>{clearInterval(timer);stop();};return stream;};
});
await context.route('**/assets/vision_bundle-*.js',r=>r.fulfill({contentType:'text/javascript',body:`export const FilesetResolver={forVisionTasks:async()=>({})};export const FaceLandmarker={createFromOptions:async()=>({close(){},detectForVideo(){const dot=document.querySelector('#eye-dot');let t=dot&&!dot.hidden?[parseFloat(dot.style.left)/100,parseFloat(dot.style.top)/100]:window.gazeTarget;if(window.freezeGaze)t=[.5,.5];const p=Array.from({length:478},()=>({x:.5,y:.5,z:0}));for(const [i,x,y] of [[33,.3,.4],[133,.4,.4],[362,.6,.4],[263,.7,.4],[159,.35,.385],[145,.35,.415],[386,.65,.385],[374,.65,.415],[1,.5,.55],[468,.33+t[0]*.04,.39+t[1]*.02],[473,.63+t[0]*.04,.39+t[1]*.02]])p[i]={x,y,z:0};return {faceLandmarks:[p],faceBlendshapes:[{categories:[{categoryName:'eyeBlinkLeft',score:window.eyeClosed?.9:0}]}]};}})};`}));
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:4173');await page.locator('#welcome-touch').click();await page.locator('#settings').click();await page.locator('#open-setup-guide').click();await page.locator('#guide-lang-en').click();await page.locator('#guide-reading-read').click();await page.locator('#guide-position-seated').click();await page.locator('#guide-input-camera').click();await page.locator('#guide-camera-eye').click();await page.locator('#guide-apply').click();await page.locator('#eye-start').click();await page.locator('#eye-begin').click();
await page.waitForFunction(()=>document.querySelector('#eye-use')?.hidden===false,{},{timeout:90000});
console.log('PASS guided 5-point calibration and held-out 4-point validation');
await page.screenshot({path:'artifacts/eye-calibration.png'});await page.locator('#eye-use').click();assert.equal(await page.locator('#practice-start').isEnabled(),true);await page.locator('#practice-close').click();assert.equal(await page.locator('#board .tile').count(),8);
const box=await page.locator('[data-phrase="yes"]').boundingBox();await page.evaluate(({x,y})=>window.gazeTarget=[x/innerWidth,y/innerHeight],{x:box.x+box.width/2,y:box.y+box.height/2});
await page.waitForFunction(()=>document.querySelector('#message').textContent==='Yes');console.log('PASS eye-only dwell selects Yes on adaptive desktop board');
async function gazeAt(selector){const b=await page.locator(selector).boundingBox();await page.evaluate(({x,y})=>window.gazeTarget=[x/innerWidth,y/innerHeight],{x:b.x+b.width/2,y:b.y+b.height/2});}
await gazeAt('#take-break');await page.waitForFunction(()=>document.querySelector('#rest-resume'));
assert.match(await page.locator('#rest-description').innerText(),/Camera stays on/);await gazeAt('#rest-resume');await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.waitForTimeout(2200);assert.equal(await page.locator('#message').innerText(),'Yes');assert.equal(await page.locator('#camera-pointer').isVisible(),true);console.log('PASS eye-only rest/resume preserves calibration without selecting through overlay');
await gazeAt('#wrong-selection');await page.waitForFunction(()=>document.querySelector('#message').textContent==='That was a wrong selection. It is not what I meant.');
await gazeAt('#say-wait');await page.waitForFunction(()=>document.querySelector('#message').textContent==='Please give me time to answer.');console.log('PASS eye-only correction and waiting controls');
await gazeAt('#dock-setup');await page.waitForFunction(()=>document.querySelector('#modal').open);
await gazeAt('[data-scroll="1"]');await page.waitForFunction(()=>document.querySelector('#modal').scrollTop>0,{},{timeout:12000});console.log('PASS eye-controlled setup navigation and scrolling');await page.locator('#close-dialog').click();
await page.screenshot({path:'artifacts/eye-board.png'});await page.evaluate(()=>window.eyeClosed=true);await page.waitForTimeout(250);assert.equal(await page.locator('#camera-pointer').isVisible(),false);assert.equal(await page.locator('.dwelling').count(),0);console.log('PASS closed-eye sample cancels selection');
await page.setViewportSize({width:1300,height:900});await page.waitForTimeout(250);assert.equal(await page.locator('#camera-pointer').isVisible(),false);assert.match(await page.locator('#input-hint').innerText(),/Screen size changed/);console.log('PASS resize requires recalibration');
await page.locator('#change-input').click();await page.locator('#eye-start').click();await page.evaluate(()=>window.eyeClosed=false);await page.locator('#eye-begin').click();await page.waitForFunction(()=>document.querySelector('#eye-status')?.textContent.includes('Accuracy check'),{},{timeout:70000});await page.evaluate(()=>window.freezeGaze=true);await page.waitForFunction(()=>document.querySelector('#eye-retry')?.hidden===false,{},{timeout:40000});assert.equal(await page.locator('#eye-use').isVisible(),false);console.log('PASS inaccurate validation blocks eye activation');
await page.locator('#eye-exit').click();await page.locator('[data-phrase="no"]').click();assert.equal(await page.locator('#message').innerText(),'No');assert.deepEqual(errors,[]);console.log('PASS cancel preserves touch fallback, no runtime errors');
await writeFile('artifacts/eye-results.json',JSON.stringify({passed:6,input:'Generated video and simulated face landmarks. Not a real-person gaze accuracy measurement.'},null,2));await browser.close();

