import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext(),page=await context.newPage();await page.goto('http://localhost:4173');await page.locator('#welcome-setup').click();await page.locator('#guide-lang-es').click();await page.locator('#guide-reading-larger').click();const settings=await page.evaluate(()=>localStorage.getItem('reach-settings'));await page.reload();await page.locator('#welcome-setup').click();await page.locator('#guide-position-reclined').waitFor();assert.equal(await page.locator('#dialog-body').getAttribute('lang'),'es');assert.equal(await page.evaluate(()=>localStorage.getItem('reach-settings')),settings);
 await page.locator('#guide-position-reclined').click();await page.locator('#guide-input-camera').click();await page.locator('#guide-camera-eye').click();await page.locator('#guide-back').click();await page.reload();await page.locator('#welcome-setup').click();await page.locator('#guide-camera-eye').waitFor();await page.locator('#guide-cancel').click();assert.equal(await page.evaluate(()=>sessionStorage.getItem('reach-guide-draft-v1')),null);
 await page.locator('#settings').click();await page.locator('#open-setup-guide').click();await page.locator('#guide-lang-en').click();await page.locator('#guide-reading-read').click();await page.locator('#guide-position-seated').click();await page.locator('#guide-input-touch').click();await page.locator('#guide-apply').click();await page.locator('#practice-start').waitFor();assert.equal(await page.evaluate(()=>sessionStorage.getItem('reach-guide-draft-v1')),null);
 await page.locator('#practice-close').click();await page.locator('#settings').click();await page.evaluate(()=>{sessionStorage.setItem('reach-guide-draft-v1',JSON.stringify({person:'another-person',draft:{step:5,answers:{language:'ar',reading:'read',position:'seated',method:'eye'}}}));});await page.locator('#open-setup-guide').click();await page.locator('#guide-lang-en').waitFor();assert.equal(await page.locator('#dialog-body').getAttribute('lang'),'en');
 await page.evaluate(()=>{const write=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='reach-guide-draft-v1')throw new DOMException('Full','QuotaExceededError');return write.call(this,k,v);};});await page.locator('#guide-lang-en').click();assert.match(await page.locator('#guide-draft-status').textContent(),/could not be kept/);await page.locator('#guide-reading-read').waitFor();
 console.log('PASS same-tab guide restoration without applying settings, camera Back restoration, cancel/apply cleanup, other-person isolation and storage-failure feedback');
}finally{await browser.close();}
