import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();
 await page.addInitScript(()=>{window.spoken=[];window.audioPlays=0;window.SpeechSynthesisUtterance=function(text){this.text=text;};speechSynthesis.getVoices=()=>[{lang:'en-US',name:'Test English',localService:true}];speechSynthesis.speak=u=>spoken.push(u.text);const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){audioPlays++;return play.call(this);};});
 const original=JSON.parse(await readFile('tests/fixtures/reach-media.obf','utf8'));original.buttons[2].vocalization='Please listen to my full message.';const raw=JSON.stringify(original);const upload=data=>page.locator('#board-import-file').setInputFiles({name:'example.obf',mimeType:'application/json',buffer:Buffer.from(data)});
 await page.goto('http://localhost:4173');await page.locator('#welcome-touch').click();const open=async()=>{await page.locator('#settings').click();await page.locator('#open-imported-boards').click();};await open();
 const bad=structuredClone(original);bad.buttons[0].actions=[':clear'];await upload(JSON.stringify(bad));await page.locator('#import-board-save').waitFor();assert.equal(await page.locator('#import-board-save').isDisabled(),true);await page.locator('#import-review-cancel').click();assert.equal(await page.locator('[id^=open-board-]').count(),0);
 await upload(raw);await page.locator('#import-board-save').click();await page.locator('[id^=open-board-]').waitFor();const id=(await page.locator('[id^=open-board-]').getAttribute('id')).slice('open-board-'.length);await page.locator('#open-board-'+id).click();await page.locator('#imported-slot-1').click();assert.equal(await page.locator('#imported-message').textContent(),'Yes');assert.equal(await page.evaluate(()=>audioPlays),0);await page.locator('#imported-speak').click();await page.waitForFunction(()=>audioPlays===1);assert.equal(await page.locator('#message').textContent(),'Yes');await page.locator('#imported-stop').click();
 assert.match(await page.locator('#imported-voice-status').textContent(),/stopped/i);
 await page.locator('#imported-slot-3').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement?.id),'imported-slot-3');assert.equal(await page.locator('#imported-slot-3').getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>spoken.length),0);
 await page.locator('#imported-slot-3').click();assert.match(await page.locator('#imported-slot-3').textContent(),/My special message/);assert.equal(await page.locator('#imported-message').textContent(),'Please listen to my full message.');await page.locator('#imported-speak').click();assert.equal(await page.evaluate(()=>spoken.at(-1)),'Please listen to my full message.');assert.equal(await page.locator('#imported-grid .empty-position').count(),1);
 await page.locator('#imported-slot-3 img').evaluate(img=>{img.src='data:image/png;base64,AAAA';});await page.locator('#imported-slot-3 .imported-media-error').waitFor();assert.match(await page.locator('#imported-slot-3').textContent(),/Image unavailable.*My special message/);
 for(const id of ['imported-speak','imported-stop','imported-help'])assert.ok((await page.locator('#'+id).boundingBox()).height>=64);
 const accessibility=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(accessibility.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),[]);await page.screenshot({path:'artifacts/imported-board-viewer.png'});await page.locator('#imported-next').click();assert.equal(await page.locator('#imported-slot-5').count(),1);await page.locator('#imported-back').click();
 const event=page.waitForEvent('download');await page.locator('#download-board-'+id).click();assert.equal(await readFile(await (await event).path(),'utf8'),raw);
 await page.locator('#imported-close').click();await page.reload();await open();await page.locator('#open-board-'+id).waitFor();assert.equal(await page.locator('#open-board-'+id).count(),1);await page.locator('#delete-board-'+id).click();await page.locator('#cancel-board-remove').click();await page.locator('#open-board-'+id).waitFor();await page.locator('#delete-board-'+id).click();await page.locator('#confirm-board-remove').click();await page.locator('#open-board-'+id).waitFor({state:'detached'});
 console.log('PASS import review blocks actions, explicit save, recorded/TTS routing, original label versus speech, empty slots/pages, exact original download, reload, deliberate removal and accessibility');
}finally{await browser.close();}

