import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:4173');await page.locator('#welcome-touch').click();
for(const [lang,text] of [['zh','是'],['hi','हाँ'],['es','Sí'],['ar','نعم'],['th','ใช่'],['en','Yes']]){await page.locator('#language').click();await page.locator(`[data-lang="${lang}"]`).click();await page.locator('#quick-done').click();await page.locator('[data-phrase="yes"]').click();assert.equal(await page.locator('#message').innerText(),text);assert.equal(await page.locator('html').getAttribute('dir'),lang==='ar'?'rtl':'ltr');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
console.log('PASS six languages, speech text and Arabic layout');
await page.locator('#dock-setup').click();assert.equal(await page.locator('[data-profile]').count(),3);await page.locator('[data-profile="hospital"]').click();await page.locator('#quick-done').click();await page.locator('[data-scroll="1"]').click();assert.equal(await page.locator('[data-phrase="nurse"]').count(),1);assert.equal(await page.locator('[data-phrase="suction"]').count(),1);
await page.locator('#dock-setup').click();await page.locator('[data-profile="family"]').click();await page.locator('#quick-done').click();await page.locator('[data-scroll="1"]').click();assert.equal(await page.locator('[data-phrase="photos"]').count(),1);assert.equal(await page.locator('[data-phrase="suction"]').count(),0);console.log('PASS home, hospital and family phrase banks');await page.locator('#dock-home').click();
await page.locator('#change-input').click();await page.locator('[value="dwell"]').check();await page.locator('#dwell-time').fill('600');await page.locator('#input-done').click();await page.evaluate(()=>scrollTo(0,0));await page.locator('[data-scroll="1"]').hover();await page.waitForTimeout(1500);assert.match(await page.locator('#page-status').innerText(),/2 \/ 3/);await page.mouse.move(0,0);await page.locator('[data-scroll="-1"]').hover();await page.waitForTimeout(1500);assert.equal(await page.evaluate(()=>scrollY),0);console.log('PASS dwell page navigation without dragging');
await page.mouse.move(0,0);await page.locator('#dock-setup').click();await page.evaluate(()=>document.querySelector('#modal').scrollTop=0);await page.locator('[data-scroll="1"]').hover();await page.waitForTimeout(900);assert.ok(await page.locator('#modal').evaluate(e=>e.scrollTop)>100);await page.mouse.move(0,0);await page.locator('[data-scroll="-1"]').hover();await page.waitForTimeout(1500);assert.equal(await page.locator('#modal').evaluate(e=>e.scrollTop),0);await page.mouse.move(0,0);console.log('PASS dock scroll works inside modal setup');
await page.screenshot({path:'artifacts/navigation-setup.png',fullPage:true});await page.locator('#quick-done').click();await page.locator('#language').click();await page.locator('[data-lang="ar"]').click();await page.locator('#quick-done').click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'artifacts/arabic-phone.png',fullPage:true});
const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(audit.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);assert.deepEqual(errors,[]);console.log('PASS Arabic phone accessibility and runtime checks');
await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'ar');await page.locator('[data-scroll="1"]').click();assert.equal(await page.locator('[data-phrase="photos"]').count(),1);await writeFile('artifacts/navigation-results.json',JSON.stringify({passed:6,language:'All 6 languages; Arabic RTL',input:'Browser pointer dwell; camera mapping covered separately'},null,2));await browser.close();
