import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('reach-welcomed','1');window.audioLog=[];window.permissionCalls=0;window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[{name:'Test local English',lang:'en-US',localService:true}],cancel:()=>{},speak:u=>audioLog.push(u.text),addEventListener:()=>{},removeEventListener:()=>{}}});navigator.mediaDevices.getUserMedia=async()=>{permissionCalls++;const c=document.createElement('canvas');c.width=640;c.height=480;c.getContext('2d').fillRect(0,0,640,480);return c.captureStream(20);};});
 await page.goto('http://localhost:4173');await page.waitForFunction(()=>!!navigator.serviceWorker.controller);const open=async()=>{await page.locator('#settings').click();await page.locator('#open-offline').click();await page.waitForFunction(()=>document.querySelector('#offline-state-hand'));};await open();
 assert.ok((await page.locator('#offline-state-board').textContent()).includes('Files verified'));assert.ok((await page.locator('#offline-state-hand').textContent()).includes('Still to download'));assert.equal(await page.locator('#offline-heard').isDisabled(),true);await page.locator('#offline-play').click();assert.equal(await page.evaluate(()=>audioLog.length),1);await page.locator('#offline-heard').click();assert.ok((await page.locator('#offline-voice-status').textContent()).includes('You confirmed'));await page.locator('#offline-no-sound').click();assert.ok((await page.locator('#offline-voice-status').textContent()).includes('sound not checked'));
 await page.locator('#offline-download-hand').click();await page.waitForFunction(()=>document.querySelector('#offline-state-hand').textContent.includes('Files verified'),{},{timeout:60000});assert.equal(await page.evaluate(()=>permissionCalls),0);assert.equal(await page.locator('#offline-download-hand').isDisabled(),true);
 assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id),[]);await page.screenshot({path:'artifacts/offline-readiness.png'});
 await page.evaluate(async()=>{const m=await(await fetch('/offline-manifest.json')).json();const c=await caches.open(m.trackingCache);await c.put('/tracking/hand_landmarker.task',new Response('corrupt'));});await page.locator('#offline-refresh').click();await page.waitForFunction(()=>document.querySelector('#offline-state-hand').textContent.includes('Still to download'));await page.locator('#offline-download-hand').click();await page.waitForFunction(()=>document.querySelector('#offline-state-hand').textContent.includes('Files verified'),{},{timeout:60000});
 await page.locator('#offline-done').click();await context.setOffline(true);await page.reload();await open();assert.ok((await page.locator('#offline-state-hand').textContent()).includes('Files verified'));await page.locator('#offline-done').click();await page.locator('#change-input').click();await page.locator('[value=hand]').check();await page.locator('#camera-start').click();await page.waitForFunction(()=>document.querySelector('#camera-status').textContent.includes('Show your hand'),{},{timeout:60000});await page.locator('#camera-stop').click();assert.deepEqual(errors,[]);console.log('PASS verified board/camera files, explicit voice confirmation, corrupt-cache repair, camera-free download, offline restart and actual offline hand-model initialization');
}finally{await browser.close();}
