import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import AxeBuilder from '@axe-core/playwright';import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('reach-welcomed','1');window.print=()=>window.dispatchEvent(new Event('beforeprint'));});
 const open=async()=>{await page.locator('#settings').click();await page.locator('#open-passport').click();};await page.goto('http://localhost:4173');await open();assert.ok((await page.locator('.passport-card').innerText()).includes('Not provided'));
 await page.locator('#passport-edit').click();await page.locator('#passport-yes').fill('Tap my finger once');await page.locator('#passport-discard').click();assert.equal(await page.locator('.passport-card').innerText().then(t=>t.includes('Tap my finger once')),false);
 await page.locator('#passport-edit').click();await page.locator('#passport-name').fill('<img src=x onerror=alert(1)>');await page.locator('#passport-yes').fill('Tap my finger once');await page.locator('#passport-no').fill('Tap twice');await page.locator('#passport-wait').fill('Please wait 15 seconds');await page.locator('#passport-backup').fill('Ask one question at a time and use my agreed signals.');await page.locator('#passport-save').click();assert.equal(await page.locator('.passport-card img').count(),0);
 await page.reload();await open();assert.ok((await page.locator('.passport-card').innerText()).includes('Tap my finger once'));
 const downloadPromise=page.waitForEvent('download');await page.locator('#passport-download').click();const download=await downloadPromise;await download.saveAs('artifacts/communication-card.html');const html=await fs.readFile('artifacts/communication-card.html','utf8');assert.ok(html.includes('&lt;img'));assert.equal(html.includes('<script'),false);
 await page.locator('#passport-print').click();await page.emulateMedia({media:'print'});assert.equal(await page.locator('#passport-print-sheet').isVisible(),true);assert.equal(await page.locator('#app').isVisible(),false);await page.pdf({path:'artifacts/communication-card.pdf',format:'A4'});await page.emulateMedia({media:'screen'});await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));assert.equal(await page.locator('#passport-print-sheet').count(),0);assert.equal(await page.locator('#passport-edit').isVisible(),true);
 await page.locator('#passport-close').click();await page.locator('#settings').click();await page.locator('[data-profile=hospital]').click();await page.locator('#open-passport').click();assert.ok((await page.locator('.passport-card').innerText()).includes('Tap twice'));
 await page.locator('#passport-edit').click();await page.locator('#passport-clear').click();await page.locator('#passport-discard').click();assert.ok((await page.locator('.passport-card').innerText()).includes('Tap twice'));await page.locator('#passport-close').click();
 await page.locator('#language').click();await page.locator('[data-lang=ar]').click();await page.locator('#quick-done').click();await open();assert.equal(await page.locator('.passport-card').getAttribute('dir'),'rtl');assert.ok((await page.locator('.passport-card').innerText()).includes('Tap twice'));assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id),[]);await page.screenshot({path:'artifacts/communication-card-arabic.png'});
 await page.locator('#passport-edit').click();assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id),[]);
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 assert.deepEqual(errors,[]);console.log('PASS handover save/discard/clear, escaping, persistence, separate care presets, standalone download, print isolation, Arabic accessibility and widths');
}finally{await browser.close();}
