import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.setDefaultTimeout(15000);
 await page.goto('http://localhost:4173');await page.locator('#welcome-touch').click();await page.locator('#settings').click();await page.locator('#quick-advanced').click();await page.locator('#open-phrases').click();await page.locator('#create-personal-phrase').click();await page.locator('#edit-text-en').fill('My family');
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=800;c.height=600;const ctx=c.getContext('2d');ctx.fillStyle='#1b6d53';ctx.fillRect(0,0,800,600);ctx.fillStyle='white';ctx.fillRect(200,100,400,400);return c.toDataURL().split(',')[1];});
 const upload=()=>page.locator('#edit-photo-file').setInputFiles({name:'family.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await upload();await page.locator('#edit-photo-preview').waitFor();const photo=await page.locator('#edit-photo-preview').getAttribute('src');assert.ok(photo.length<=16000);assert.ok(photo.startsWith('data:image/jpeg;base64,/9j/'));assert.deepEqual(await page.locator('#edit-photo-preview').evaluate(img=>({width:img.naturalWidth,height:img.naturalHeight})),{width:256,height:192});
 await page.locator('#edit-photo-file').setInputFiles({name:'invalid.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await page.waitForFunction(()=>document.querySelector('#edit-photo-status').textContent.includes('could not'));assert.equal(await page.locator('#edit-photo-preview').getAttribute('src'),photo);assert.equal(await page.locator('#edit-save').isEnabled(),true);
 await page.locator('#edit-cancel').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('reach-settings')).phrases.length),0);
 await page.locator('#create-personal-phrase').click();await page.locator('#edit-text-en').fill('My family');await upload();await page.locator('#edit-photo-preview').waitFor();await page.locator('#edit-save').click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('reach-settings')).phrases[0]);assert.equal(saved.photo,photo);await page.locator('#phrases-done').click();await page.reload();await page.locator('#board-topics').click();await page.locator('#modal [data-category=mine]').click();await page.locator('.phrase-photo').waitFor();assert.equal(await page.locator('.phrase-photo').getAttribute('src'),photo);await page.screenshot({path:'artifacts/personal-photo-board.png'});
 console.log('PASS local photo resize, aspect ratio, failed replacement preservation, draft discard, save and reload');
}finally{await browser.close();}
