import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.setItem('reach-welcomed','1'));await page.goto('http://localhost:4173');await page.locator('[data-phrase=yes]').click();
 await page.locator('#settings').click();await page.locator('#quick-practice').click();await page.locator('#practice-start').click();await page.locator('#practice-target-3').click();
 for(const i of [0,3,1,2])await page.locator(`#practice-target-${i}`).click();await page.locator('#practice-rest').click();await page.locator('#practice-target-0').click();await page.waitForSelector('.practice-results',{timeout:16000});
 assert.deepEqual(await page.locator('.practice-results dd').allTextContents().then(a=>[a[0],a[1],a[3]]),['4/4','1','1']);assert.equal(await page.locator('#message').innerText(),'Yes');
 await page.locator('#practice-helper').click();assert.equal(await page.locator('#practice-helper').getAttribute('aria-pressed'),'true');
 const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(audit.violations.map(v=>v.id),[]);await page.screenshot({path:'artifacts/input-practice-results.png'});
 await page.locator('#practice-slower').click();assert.equal(await page.locator('#dwell-time').inputValue(),'1800');await page.locator('#input-done').click();assert.equal(await page.locator('#message').innerText(),'Yes');console.log('PASS measured practice, assistance disclosure, explicit timing adjustment and preserved communication');
 await page.locator('#change-input').click();await page.locator('[value=hand]').check();await page.locator('#input-done').click();await page.locator('#settings').click();await page.locator('#quick-practice').click();assert.equal(await page.locator('#practice-start').isDisabled(),true);await page.locator('#practice-change').click();assert.equal(await page.locator('#camera-start').isVisible(),true);console.log('PASS unconfigured camera cannot produce a practice result');
 await page.locator('[value=dwell]').check();await page.locator('#dwell-time').fill('600');await page.locator('#input-done').click();await page.locator('#settings').click();await page.locator('#quick-practice').click();await page.locator('#practice-start').hover();await page.waitForSelector('#practice-target-0');
 for(const i of [0,3,1,2]){await page.mouse.move(0,0);await page.locator(`#practice-target-${i}`).hover();await page.waitForTimeout(900);}
 assert.equal(await page.locator('#practice-rest').isVisible(),true);await page.mouse.move(0,0);await page.locator('#practice-close').click();assert.deepEqual(errors,[]);console.log('PASS dwell practice targets and cancel preserve access');
 await page.locator('#change-input').click();await page.locator('[value=switch]').check();await page.locator('#scan-time').fill('1000');await page.locator('#input-done').click();await page.locator('#settings').click();await page.locator('#quick-practice').click();await page.locator('#practice-start').click();
 await page.waitForFunction(()=>document.querySelector('#practice-target-0').classList.contains('scanning'),{},{timeout:16000});await page.keyboard.press('Space');assert.match(await page.locator('#practice-status').innerText(),/1\/4/);await page.locator('#practice-close').click();assert.equal(await page.locator('#scan-start').innerText(),'Start scanning');console.log('PASS switch practice and restoration of prior scanning state');
}finally{await browser.close();}
