import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await context.addInitScript(()=>localStorage.setItem('reach-welcomed','1'));await page.goto('http://localhost:4173');
 await page.locator('#write-message').click();await page.locator('#compose-text').fill('Private first-person message');await page.locator('#compose-save').click();await page.locator('#compose-speak').click();await page.locator('#compose-close').click();
 await page.locator('#change-input').click();await page.locator('[value=motion]').check();await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=240;window.profileStream=canvas.captureStream(10);return profileStream;};});await page.locator('#camera-start').click();await page.waitForFunction(()=>window.profileStream?.getTracks()[0].readyState==='live');await page.locator('#input-done').click();
 const open=async()=>{await page.locator('#settings').click();await page.locator('#open-people').click();};await open();await page.locator('#person-name').fill('Alex');await page.locator('#person-rename').click();await page.locator('#person-name').fill('Bo');await page.locator('#person-create').click();assert.equal(await page.evaluate(()=>profileStream.getTracks()[0].readyState),'ended');assert.ok((await page.locator('#open-people').textContent()).includes('Bo'));await page.locator('#quick-done').click();
 assert.equal(await page.locator('#message-secondary').textContent(),'');assert.equal(await page.locator('#repeat').isDisabled(),true);assert.equal(await page.locator('#partner-view').isDisabled(),true);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('reach-settings')).phrases.length),0);
 await page.locator('#write-message').click();assert.equal(await page.locator('#compose-text').inputValue(),'');await page.locator('#compose-text').fill('Bo draft');await page.locator('#compose-close').click();await page.locator('#language').click();await page.locator('[data-lang=ar]').click();await page.locator('#quick-done').click();await open();
 assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id),[]);await page.screenshot({path:'artifacts/people-profiles.png'});
 await page.locator('[data-person=original]').click();await page.locator('#quick-done').click();assert.equal(await page.locator('#language').textContent(),'English');await page.locator('#write-message').click();assert.equal(await page.locator('#compose-text').inputValue(),'Private first-person message');await page.locator('#compose-close').click();
 const other=await context.newPage();await other.goto('http://localhost:4173');await open();const second=await page.locator('[data-person]').evaluateAll(els=>els.map(e=>e.dataset.person).find(id=>id!=='original'));await page.locator(`[data-person="${second}"]`).click();await other.waitForFunction(()=>document.documentElement.lang==='ar');assert.equal(await other.locator('#message-secondary').textContent(),'');await other.close();
 await page.locator('#quick-done').click();await page.locator('#write-message').click();assert.equal(await page.locator('#compose-text').inputValue(),'Bo draft');await page.locator('#compose-close').click();await open();await page.locator('[data-remove-person=original]').click();assert.equal(await page.locator('#person-delete-confirm').isVisible(),true);await page.locator('#person-delete-confirm').click();await page.locator('[data-person=original]').waitFor({state:'detached'});assert.equal(await page.locator('[data-person=original]').count(),0);assert.equal(await page.locator('[data-person]').count(),1);
 await page.reload();await open();assert.equal(await page.locator('[data-person]').count(),1);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('reach-profiles-v1')).people[0].draft.text),'Bo draft');
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}assert.deepEqual(errors,[]);console.log('PASS isolated phrases/drafts/languages, rename/create/switch/remove, message clearing, reload, other-tab refresh, Arabic accessibility and widths');
}finally{await browser.close();}
