import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('reach-welcomed','1');const RealAudio=window.Audio;window.recordedPlays=0;window.Audio=function(...args){const a=new RealAudio(...args),play=a.play.bind(a);a.play=()=>{recordedPlays++;window.lastAudio=a;return play();};return a;};navigator.mediaDevices.getUserMedia=async()=>{const ac=new AudioContext(),osc=ac.createOscillator(),dest=ac.createMediaStreamDestination();osc.connect(dest);osc.start();window.testMic=dest.stream;window.testAudioContext=ac;return dest.stream;};});
 await page.goto('http://localhost:4173');const open=async()=>{await page.locator('#settings').click();await page.locator('#open-recordings').click();};await open();await page.locator('#record-phrase-yes').click();assert.equal(await page.locator('#record-save').isDisabled(),true);await page.locator('#record-start').click();await page.waitForTimeout(700);await page.locator('#record-stop').click();await page.waitForFunction(()=>!document.querySelector('#record-preview').disabled);assert.equal(await page.evaluate(()=>testMic.getTracks()[0].readyState),'ended');assert.equal(await page.locator('#record-save').isDisabled(),true);await page.locator('#record-preview').click();await page.locator('#record-save').click();await page.waitForFunction(()=>document.querySelector('#recording-status').textContent.includes('saved'));assert.equal(await page.locator('#record-download').isDisabled(),false);await page.locator('#record-done').click();
 const before=await page.evaluate(()=>recordedPlays);await page.locator('[data-phrase=yes]').click();assert.equal(await page.evaluate(()=>recordedPlays),before+1);assert.ok((await page.locator('#speech-status').textContent()).includes('Saved recording'));await page.locator('#stop-speaking').click();assert.equal(await page.evaluate(()=>lastAudio.paused),true);
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.waitForTimeout(200);await page.locator('[data-phrase=yes]').click();assert.ok((await page.locator('#speech-status').textContent()).includes('Saved recording'));
 await open();await page.locator('#record-phrase-yes').click();assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id),[]);await page.screenshot({path:'artifacts/recorded-speech.png'});await page.locator('#record-start').click();await page.waitForFunction(()=>window.testMic?.getTracks()[0].readyState==='live');await page.locator('#record-done').click();assert.equal(await page.evaluate(()=>testMic.getTracks()[0].readyState),'ended');
 await page.locator('#settings').click();await page.locator('#open-people').click();await page.locator('#person-name').fill('Other person');await page.locator('#person-create').click();await page.locator('#quick-done').click();const plays=await page.evaluate(()=>recordedPlays);await page.locator('[data-phrase=yes]').click();assert.equal(await page.evaluate(()=>recordedPlays),plays);await page.locator('#settings').click();await page.locator('#open-people').click();await page.locator('[data-person=original]').click();await page.locator('#quick-done').click();await open();await page.locator('#record-phrase-yes').click();await page.locator('#record-remove').click();await page.waitForFunction(()=>document.querySelector('#record-download').disabled);await page.locator('#record-done').click();const removed=await page.evaluate(()=>recordedPlays);await page.locator('[data-phrase=yes]').click();assert.equal(await page.evaluate(()=>recordedPlays),removed);assert.deepEqual(errors,[]);console.log('PASS real MediaRecorder capture from generated audio, preview-before-save, persistent playback, Stop, microphone release on close, profile isolation, deletion and accessibility');
}finally{await browser.close();}
