import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();await page.addInitScript(()=>{window.requests=0;Object.defineProperty(navigator,'wakeLock',{value:{request:async()=>{requests++;if(window.denyWake)throw Error('Denied');const lock=new EventTarget();lock.released=false;lock.release=async()=>{lock.released=true;lock.dispatchEvent(new Event('release'));};window.testLock=lock;return lock;}}});});
 await page.goto('http://localhost:4173');await page.locator('#welcome-touch').click();await page.locator('#settings').click();assert.equal(await page.evaluate(()=>requests),0);await page.locator('#awake-enable').click();assert.equal(await page.locator('#awake-status').textContent(),'Keeping screen awake');assert.equal(await page.locator('#awake-enable').isDisabled(),true);await page.locator('#quick-done').click();await page.locator('#settings').click();assert.equal(await page.locator('#awake-status').textContent(),'Keeping screen awake');await page.evaluate(()=>testLock.release());assert.match(await page.locator('#awake-status').textContent(),/Device released/);assert.equal(await page.locator('#awake-enable').isEnabled(),true);
 await page.evaluate(()=>window.denyWake=true);await page.locator('#awake-enable').click();assert.match(await page.locator('#awake-status').textContent(),/Could not change/);await page.evaluate(()=>window.denyWake=false);await page.locator('#awake-enable').click();await page.locator('#awake-disable').click();assert.equal(await page.locator('#awake-status').textContent(),'Screen follows device sleep settings');assert.equal(await page.evaluate(()=>testLock.released),true);
 assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id),[]);assert.equal(await page.locator('#modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);await page.reload();assert.equal(await page.evaluate(()=>requests),0);
 console.log('PASS opt-in screen-awake controls, status after reopen/system release/denial, retry, explicit release, no automatic reload request and narrow accessibility');
}finally{await browser.close();}
