import {test} from 'node:test';import assert from 'node:assert/strict';
import {ScreenAwake} from '../src/screen-awake.js';
const sentinel=()=>{const lock=new EventTarget();lock.released=false;lock.release=async()=>{lock.released=true;lock.dispatchEvent(new Event('release'));};return lock;};
test('wake request is opt-in, reports system release, and retries explicitly',async()=>{let calls=0;const control=new ScreenAwake({request:async()=>{calls++;return sentinel();}});assert.equal(calls,0);await control.enable();assert.equal(control.status,'active');await control.lock.release();assert.equal(control.status,'released');assert.equal(calls,1);await control.enable();assert.equal(calls,2);await control.release();assert.equal(control.status,'off');assert.equal(control.wanted,false);});
test('late request cannot reactivate after cancellation',async()=>{let resolve;const lock=sentinel(),control=new ScreenAwake({request:()=>new Promise(r=>resolve=r)});const pending=control.enable();await control.release();resolve(lock);await pending;assert.equal(lock.released,true);assert.equal(control.lock,null);assert.equal(control.status,'off');});
test('hidden tabs release and visible tabs reacquire only while requested',async()=>{let visible=true;const control=new ScreenAwake({request:async()=>sentinel()},()=>visible);await control.enable();visible=false;await control.visibilityChanged();assert.equal(control.status,'suspended');visible=true;await control.visibilityChanged();assert.equal(control.status,'active');await control.release();await control.visibilityChanged();assert.equal(control.status,'off');});
test('unsupported and denied requests stay honest',async()=>{const unsupported=new ScreenAwake(null);await unsupported.enable();assert.equal(unsupported.status,'unsupported');const denied=new ScreenAwake({request:async()=>{throw Error('Denied');}});await denied.enable();assert.equal(denied.status,'failed');assert.equal(denied.lock,null);});
test('an old release completing cannot overwrite a newer active request',async()=>{
 let finish;const old=sentinel(),next=sentinel();old.release=()=>{old.released=true;old.dispatchEvent(new Event('release'));return new Promise(resolve=>finish=resolve);};let count=0;const control=new ScreenAwake({request:async()=>count++?next:old});await control.enable();const stopping=control.release();await control.enable();assert.equal(control.lock,next);finish();await stopping;assert.equal(control.status,'active');assert.equal(control.lock,next);
});
test('an old release rejection cannot overwrite a newer active request',async()=>{
 let reject;const old=sentinel(),next=sentinel();old.release=()=>{old.released=true;old.dispatchEvent(new Event('release'));return new Promise((resolve,r)=>reject=r);};let count=0;const control=new ScreenAwake({request:async()=>count++?next:old});await control.enable();const stopping=control.release();await control.enable();reject(Error('Late rejection'));await stopping;assert.equal(control.status,'active');assert.equal(control.lock,next);
});
