import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:4173');await page.locator('#welcome-setup').click();assert.equal(await page.locator('#guide-lang-th').isVisible(),true);await page.locator('#guide-lang-ar').click();await page.locator('#guide-reading-larger').click();await page.locator('#guide-position-reclined').click();await page.locator('#guide-input-dwell').click();assert.equal(await page.locator('#dialog-body').getAttribute('dir'),'rtl');
 assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id),[]);await page.screenshot({path:'artifacts/setup-guide-review.png'});await page.locator('#guide-cancel').click();assert.equal(await page.locator('#language').textContent(),'English');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('reach-settings')).mode),'touch');
 const open=async()=>{await page.locator('#settings').click();await page.locator('#open-setup-guide').click();};await open();await page.locator('#guide-lang-en').click();await page.locator('#guide-reading-read').click();await page.locator('#guide-position-seated').click();await page.locator('#guide-input-switch').click();await page.locator('#guide-apply').click();assert.equal(await page.locator('#practice-start').isEnabled(),true);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('reach-settings')).mode),'switch');await page.locator('#practice-close').click();
 await open();await page.locator('#guide-lang-en').click();await page.locator('#guide-reading-larger').click();await page.locator('#guide-position-changing').click();await page.locator('#guide-input-camera').click();await page.locator('#guide-camera-hand').click();await page.locator('#guide-apply').click();assert.equal(await page.locator('#camera-start').isVisible(),true);await page.locator('#input-done').click();assert.equal(await page.locator('#practice-start').isDisabled(),true);await page.locator('#practice-close').click();
 await open();await page.locator('#guide-lang-en').click();await page.locator('#guide-reading-partner').click();await page.locator('#guide-position-reclined').click();await page.locator('#guide-input-helper').click();await page.locator('#guide-apply').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('reach-settings')).setupGuide.helper),true);await page.locator('#practice-close').click();await page.locator('#change-input').click();await page.locator('#input-done').click();assert.equal(await page.locator('#modal').isVisible(),false);
 await page.locator('#change-input').click();await page.locator('[value=dwell]').check();await page.locator('#dwell-time').fill('600');await page.locator('#input-done').click();await open();await page.mouse.move(0,0);await page.locator('#guide-lang-en').hover();await page.waitForTimeout(1700);assert.equal(await page.locator('#guide-reading-read').isVisible(),true);assert.equal(await page.locator('#guide-position-seated').count(),0);await page.mouse.move(0,0);
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}assert.deepEqual(errors,[]);console.log('PASS first-run guide, unapplied cancellation, RTL accessibility, switch practice, camera calibration gate, helper setup, no leaked practice routing, dwell release and widths');
}finally{await browser.close();}
