import {recordingKey,RecordedOutput} from './recordings.js';
export const AUDIO_BACKUP_LIMIT=15_000_000;
const languages=['en','zh','hi','es','ar','th'];
export async function encodeAudioBackup(clips){const recordings=[];for(const clip of clips){const bytes=new Uint8Array(await clip.blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));recordings.push({phrase:clip.phrase,language:clip.language,text:clip.text,mimeType:clip.blob.type,data:btoa(binary)});}return {app:'Reach recordings',version:1,recordings};}
export function decodeAudioBackup(data){if(data?.app!=='Reach recordings'||data.version!==1||!Array.isArray(data.recordings)||data.recordings.length>100)throw Error('Choose a Reach recordings backup with up to 100 clips.');const seen=new Set();let total=0;return data.recordings.map(entry=>{if(!entry||typeof entry.phrase!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(entry.phrase)||!languages.includes(entry.language)||typeof entry.text!=='string'||!entry.text.trim()||Array.from(entry.text).length>500||typeof entry.mimeType!=='string'||!/^audio\/(?:webm|mp4|ogg|wav)(?:;codecs=[a-zA-Z0-9.,_-]+)?$/.test(entry.mimeType)||typeof entry.data!=='string'||entry.data.length>2_666_668||(entry.data.length%4!==0||!/^[A-Za-z0-9+/]*={0,2}$/.test(entry.data)))throw Error('The backup contains an invalid recording. Nothing was imported.');const key=recordingKey(entry.phrase,entry.language);if(seen.has(key))throw Error('The backup repeats a phrase and language. Nothing was imported.');seen.add(key);const binary=atob(entry.data),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));total+=bytes.length;if(!bytes.length||bytes.length>2_000_000||total>10_000_000)throw Error('Recordings exceed the 2 MB clip or 10 MB total limit.');return {phrase:entry.phrase,language:entry.language,text:entry.text,blob:new Blob([bytes],{type:entry.mimeType})};});}
export function matchAudioBackup(clips,phrases,textFor){return clips.map(clip=>({...clip,matches:phrases.some(p=>p.id===clip.phrase&&textFor(p,clip.language)===clip.text)}));}
const labels={
 title:['Back up recordings','备份录音','रिकॉर्डिंग का बैकअप','Copias de grabaciones','نسخ التسجيلات احتياطياً','สำรองเสียงบันทึก'],
 intro:['Export all recordings for the current person. On another device, import their setup first, then this audio backup. Imports match exact phrase IDs, languages and text. Unmatched clips are skipped. Existing clips are kept unless you choose to replace them.','导出当前使用者的全部录音。在另一设备上，先导入设置，再导入音频备份。仅匹配短语编号、语言和原文完全一致的录音。不匹配的将跳过。除非选择替换，否则保留现有录音。','वर्तमान व्यक्ति की सभी रिकॉर्डिंग निर्यात करें। दूसरे डिवाइस पर पहले सेटअप, फिर ऑडियो बैकअप आयात करें। वाक्य आईडी, भाषा और पाठ का ठीक मिलान होता है। बेमेल क्लिप छोड़ दी जाती हैं। बदलने का विकल्प न चुनें तो मौजूदा क्लिप रखी जाती हैं।','Exporta todas las grabaciones de la persona actual. En otro dispositivo, importa primero su configuración y después este audio. Se exige coincidencia exacta de frase, idioma y texto. Se omiten las que no coinciden y se conservan las existentes salvo que elijas reemplazarlas.','صدّر تسجيلات الشخص الحالي. على جهاز آخر، استورد إعداداته أولاً ثم نسخة الصوت. يجب تطابق معرّف العبارة واللغة والنص تماماً. تُتخطى المقاطع غير المطابقة وتُحفظ المقاطع الحالية ما لم تختر استبدالها.','ส่งออกเสียงทั้งหมดของผู้ใช้ปัจจุบัน บนอุปกรณ์ใหม่ให้นำเข้าการตั้งค่าก่อนแล้วจึงนำเข้าเสียง รหัสข้อความ ภาษา และข้อความต้องตรงกัน ข้ามคลิปที่ไม่ตรง และเก็บคลิปเดิมไว้เว้นแต่เลือกแทนที่'],
 export:['Download recording backup','下载录音备份','रिकॉर्डिंग बैकअप डाउनलोड करें','Descargar copia de grabaciones','تنزيل نسخة التسجيلات','ดาวน์โหลดสำรองเสียง'],
 file:['Choose recording backup','选择录音备份','रिकॉर्डिंग बैकअप चुनें','Elegir copia de grabaciones','اختيار نسخة التسجيلات','เลือกไฟล์สำรองเสียง'],
 matched:['Matching clips','匹配录音','मिलती क्लिप','Grabaciones coincidentes','المقاطع المطابقة','คลิปที่ตรงกัน'],
 unmatched:['Unmatched — will not import','不匹配 — 不导入','मेल नहीं — आयात नहीं होगा','Sin coincidencia: no se importará','غير مطابق — لن يُستورد','ไม่ตรงกัน — ไม่นำเข้า'],
 existing:['Already saved','已保存','पहले से सहेजा','Ya guardada','محفوظ مسبقاً','มีอยู่แล้ว'],
 replace:['Replace matching saved recordings','替换匹配的已保存录音','मिलती सहेजी रिकॉर्डिंग बदलें','Reemplazar grabaciones coincidentes','استبدال التسجيلات المطابقة المحفوظة','แทนที่เสียงเดิมที่ตรงกัน'],
 apply:['Import matching recordings','导入匹配录音','मिलती रिकॉर्डिंग आयात करें','Importar grabaciones coincidentes','استيراد التسجيلات المطابقة','นำเข้าเสียงที่ตรงกัน'],
 preview:['Preview','试听','सुनें','Escuchar','معاينة','ฟัง'],stop:['Stop playback','停止播放','आवाज़ रोकें','Detener reproducción','إيقاف التشغيل','หยุดเล่น'],
 imported:['Recordings imported','录音已导入','रिकॉर्डिंग आयात हुईं','Grabaciones importadas','تم استيراد التسجيلات','นำเข้าเสียงแล้ว'],
 done:['Done','完成','हो गया','Listo','تم','เสร็จ'],
};
export const audioBackupText=(key,lang='en')=>labels[key]?.[languages.indexOf(lang)]||labels[key]?.[0]||key;
export function mountAudioBackup(root,{library,language,phrases,textFor,onClose,onStop,onTransition}){
 const t=k=>audioBackupText(k,language),person=library.person,output=new RecordedOutput();let entries=[],replace=false,disposed=false,loading=false,readGeneration=0;
 const b=(id,label,action)=>{const el=document.createElement('button');el.id=id;el.className='secondary-button';el.textContent=label;el.dataset.access='';el.onclick=()=>action(el);return el;};
 root.innerHTML='<p class="intro"></p><div id="audio-backup-actions" class="backup-row"></div><p id="audio-backup-status" role="status"></p><div id="audio-backup-preview"></div>';root.querySelector('.intro').textContent=t('intro');const actions=root.querySelector('#audio-backup-actions'),status=root.querySelector('#audio-backup-status'),preview=root.querySelector('#audio-backup-preview');
 const exportButton=b('audio-export',t('export'),async()=>{try{exportButton.disabled=true;const data=await encodeAudioBackup(await library.all());if(disposed)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='reach-recordings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){if(!disposed)status.textContent=error.message;}finally{exportButton.disabled=false;}});actions.append(exportButton);
 const label=document.createElement('label');label.className='secondary-button import-label';label.textContent=t('file');const input=document.createElement('input');input.id='audio-import';input.type='file';input.accept='.json,application/json';label.append(input);actions.append(label);
 input.onchange=async()=>{if(loading)return;const generation=++readGeneration;entries=[];replace=false;output.stop();render();try{const file=input.files[0];if(!file)return;if(file.size>AUDIO_BACKUP_LIMIT)throw Error('The recording backup exceeds 15 MB.');const data=JSON.parse(await file.text());if(disposed||generation!==readGeneration)return;entries=matchAudioBackup(decodeAudioBackup(data),phrases,textFor);status.textContent=file.name;render();}catch(error){if(!disposed)status.textContent=error.message;}finally{input.value='';}};
 function render(){if(disposed)return;preview.replaceChildren();if(!entries.length)return;const matches=entries.filter(e=>e.matches),summary=document.createElement('p');summary.id='audio-match-summary';summary.textContent=`${t('matched')}: ${matches.length} / ${entries.length}`;preview.append(summary);for(const entry of entries){const row=document.createElement('div');row.className='audio-import-row';const text=document.createElement('p');text.dir='auto';text.lang=entry.language;text.textContent=entry.text;const detail=document.createElement('p');detail.textContent=`${entry.language} · ${entry.matches?library.items.has(recordingKey(entry.phrase,entry.language))?t('existing'):t('matched'):t('unmatched')}`;row.append(text,detail,b('audio-preview-'+entries.indexOf(entry),t('preview'),el=>{onTransition(el);onStop();output.play(entry.blob,()=>status.textContent='This clip could not play in this browser.');}));preview.append(row);}
  const toggle=b('audio-replace',t('replace'),el=>{onTransition(el);replace=!replace;render();});toggle.setAttribute('aria-pressed',String(replace));toggle.disabled=loading;const apply=b('audio-apply',t('apply'),async el=>{onTransition(el);loading=true;input.disabled=true;render();try{const count=await library.importClips(matches,{person,replace});if(disposed)return;entries=[];status.textContent=`${t('imported')}: ${count}`;output.stop();render();}catch(error){if(!disposed)status.textContent=error.message;}finally{loading=false;input.disabled=false;render();}});apply.disabled=loading||!matches.some(e=>replace||!library.items.has(recordingKey(e.phrase,e.language)));preview.append(toggle,apply);
 }
 actions.append(b('audio-stop',t('stop'),()=>{output.stop();onStop();}),b('audio-backup-done',t('done'),onClose));
 return {dispose(){disposed=true;output.stop();}};
}
