const p = (id,en,th,icon,tone='neutral') => ({id,en,th,icon,tone});
export const categories = [
  { id:'essentials', en:'Essentials', th:'จำเป็น', icon:'LayoutGrid', hint:'The things that matter, one touch away.', phrases:[
    p('yes','Yes','ใช่','Check','yes'),p('no','No','ไม่ใช่','X','no'),p('pain','I’m in pain','เจ็บ','HeartPulse','rose'),
    p('position','Reposition me','ช่วยขยับตัวให้หน่อย','Accessibility','blue'),p('suction','I need suction','ช่วยดูดเสมหะให้หน่อย','Wind','blue'),p('toilet','Bathroom','อยากเข้าห้องน้ำ','Bath','sand'),
    p('hot','I’m hot','ร้อน','Sun','sand'),p('cold','I’m cold','หนาว','Snowflake','blue'),p('tired','I’m tired','เหนื่อย','Moon','purple'),
    p('scared','I’m scared','กลัว','HeartHandshake','purple'),p('stay','Stay with me','อยู่เป็นเพื่อนหน่อย','Users','rose'),p('thanks','Thank you','ขอบคุณ','Heart','yes') ] },
  { id:'comfort',en:'Care & comfort',th:'การดูแล',icon:'HeartHandshake',hint:'Let someone know what would help.',phrases:[p('water','Water, please','ขอน้ำหน่อย','Droplets','blue'),p('hungry','I’m hungry','หิว','Utensils','sand'),p('mouth','My mouth is dry','ปากแห้ง','Droplet','blue'),p('itch','I’m itchy','คัน','Hand','sand'),p('blanket','A blanket, please','ขอผ้าห่มหน่อย','Bed','purple'),p('sit','Help me sit up','ช่วยพยุงให้นั่งหน่อย','Accessibility','blue'),p('lights','Turn off the light','ช่วยปิดไฟหน่อย','Lamp','sand'),p('quiet','Quiet, please','ขอเงียบ ๆ หน่อย','VolumeX','purple'),p('rest','I need to rest','อยากพัก','Moon','purple')] },
  {id:'body',en:'My body',th:'ร่างกาย',icon:'Accessibility',hint:'Choose where. Your selection will say “My … hurts.”',phrases:[p('head','My head hurts','ปวดหัว','CircleUser','rose'),p('neck','My neck hurts','ปวดคอ','Accessibility','rose'),p('chest','My chest hurts','เจ็บหน้าอก','HeartPulse','rose'),p('back','My back hurts','ปวดหลัง','Accessibility','rose'),p('stomach','My stomach hurts','ปวดท้อง','Circle','rose'),p('arm','My arm hurts','ปวดแขน','Hand','rose'),p('leg','My leg hurts','ปวดขา','Footprints','rose'),p('little','A little pain','เจ็บนิดหน่อย','Activity','sand'),p('much','A lot of pain','เจ็บมาก','Activity','no')]},
  {id:'feelings',en:'Feelings',th:'ความรู้สึก',icon:'Smile',hint:'There is room for every feeling.',phrases:[p('happy','I’m happy','มีความสุข','Smile','yes'),p('sad','I’m sad','เศร้า','Frown','blue'),p('worried','I’m worried','กังวล','Cloud','purple'),p('frustrated','I’m frustrated','หงุดหงิด','Zap','sand'),p('love','I love you','รักนะ','Heart','rose'),p('okay','I’m okay','สบายดี','ThumbsUp','yes'),p('lonely','I feel lonely','รู้สึกเหงา','User','purple'),p('bored','I’m bored','เบื่อ','Coffee','sand'),p('listen','Please listen','ช่วยฟังหน่อย','Ear','blue')]},
  {id:'people',en:'People & questions',th:'คนและคำถาม',icon:'Users',hint:'Connect with someone. Ask what you want to know.',phrases:[p('friend','I want a friend','อยากพบเพื่อน','User','yes'),p('family','I want my family','อยากพบครอบครัว','Users','rose'),p('carer','I need my caregiver','ขอพบผู้ดูแล','HeartHandshake','blue'),p('what','What is happening?','เกิดอะไรขึ้น','CircleHelp','purple'),p('where','Where are we going?','เราจะไปไหน','MapPin','blue'),p('time','What time is it?','กี่โมงแล้ว','Clock','sand'),p('again','Please say that again','ช่วยพูดอีกครั้ง','Repeat','purple'),p('understand','I understand','เข้าใจแล้ว','Check','yes'),p('notunderstand','I don’t understand','ไม่เข้าใจ','CircleHelp','sand')]},
  {id:'mine',en:'My phrases',th:'ข้อความของฉัน',icon:'Bookmark',hint:'Your people. Your routines. Your own words.',phrases:[]}
];
export const helpPhrase = p('help','I need help','ช่วยด้วย','BellRing','no');
export const scenarioPhrases=[
{...p('breath','It is hard to breathe','หายใจลำบาก','Wind','no'),translations:{zh:'我呼吸困难',hi:'मुझे साँस लेने में परेशानी है',es:'Me cuesta respirar',ar:'أجد صعوبة في التنفس'}},
{...p('nurse','I need a nurse','ขอพบพยาบาล','HeartHandshake','blue'),translations:{zh:'我需要护士',hi:'मुझे नर्स चाहिए',es:'Necesito a enfermería',ar:'أحتاج إلى ممرض أو ممرضة'}},
{...p('doctor','I want to see the doctor','ขอพบแพทย์','User','blue'),translations:{zh:'我想见医生',hi:'मुझे डॉक्टर से मिलना है',es:'Quiero ver al médico',ar:'أريد مقابلة الطبيب'}},
{...p('painrelief','Can you help with my pain?','ช่วยบรรเทาปวดได้ไหม','HeartPulse','rose'),translations:{zh:'能帮我缓解疼痛吗？',hi:'क्या आप मेरा दर्द कम करने में मदद कर सकते हैं?',es:'¿Pueden ayudarme con el dolor?',ar:'هل يمكنك مساعدتي في تخفيف الألم؟'}},
{...p('nausea','I feel sick to my stomach','คลื่นไส้','Activity','sand'),translations:{zh:'我感到恶心',hi:'मुझे मितली आ रही है',es:'Tengo náuseas',ar:'أشعر بالغثيان'}},
{...p('explain','Please explain what you are doing','ช่วยอธิบายสิ่งที่กำลังทำหน่อย','CircleHelp','purple'),translations:{zh:'请解释您在做什么',hi:'कृपया बताएं कि आप क्या कर रहे हैं',es:'Explícame lo que estás haciendo',ar:'اشرح لي ما تفعله من فضلك'}},
{...p('stop','Please stop','กรุณาหยุด','Hand','no'),translations:{zh:'请停下',hi:'कृपया रुकें',es:'Para, por favor',ar:'توقف من فضلك'}},
{...p('music','Let’s listen to music','ฟังเพลงด้วยกันนะ','Volume2','purple'),translations:{zh:'我们一起听音乐吧',hi:'आइए संगीत सुनें',es:'Escuchemos música',ar:'لنستمع إلى الموسيقى'}},
{...p('photos','Show me family photos','ขอดูรูปครอบครัว','Users','sand'),translations:{zh:'给我看看家人的照片',hi:'मुझे परिवार की तस्वीरें दिखाएँ',es:'Muéstrame fotos de la familia',ar:'أرني صور العائلة'}},
{...p('story','Tell me about your day','เล่าเรื่องวันนี้ให้ฟังหน่อย','MessageCircle','yes'),translations:{zh:'说说你今天过得怎么样',hi:'मुझे अपने दिन के बारे में बताएं',es:'Cuéntame cómo te fue hoy',ar:'حدثني عن يومك'}},
{...p('call','Can we call someone?','โทรหาใครสักคนได้ไหม','Users','blue'),translations:{zh:'我们可以给人打个电话吗？',hi:'क्या हम किसी को फोन कर सकते हैं?',es:'¿Podemos llamar a alguien?',ar:'هل يمكننا الاتصال بأحد؟'}}
];

