import {assetPath} from './asset-path.js';
export const formatBytes=n=>`${(n/1000000).toFixed(2)} MB (${n.toLocaleString()} bytes)`;
export async function validAsset(response,asset){if(!response?.ok)return false;const bytes=await response.arrayBuffer();if(bytes.byteLength!==asset.bytes)return false;const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('')===asset.sha256;}
export async function inspectAssets(cache,assets){const missing=[];for(const asset of assets)if(!await validAsset(await cache.match(asset.url),asset))missing.push(asset);return {total:assets.reduce((n,a)=>n+a.bytes,0),missingBytes:missing.reduce((n,a)=>n+a.bytes,0),missing};}
export async function prepareAssets(cache,assets,{signal,onProgress=()=>{}}={}){let completed=0;const total=assets.reduce((n,a)=>n+a.bytes,0);for(const asset of assets){signal?.throwIfAborted();if(!await validAsset(await cache.match(asset.url),asset)){const response=await fetch(asset.url,{cache:'reload',signal});if(!await validAsset(response.clone(),asset)){await cache.delete(asset.url);throw Error('Downloaded file did not match this app version. Reload and retry.');}signal?.throwIfAborted();await cache.put(asset.url,response);}completed+=asset.bytes;onProgress(completed,total);}return completed;}
const langs=['en','zh','hi','es','ar','th'];
const labels={
 title:['Offline readiness','离线准备情况','ऑफ़लाइन तैयारी','Preparación sin conexión','الجاهزية دون اتصال','ความพร้อมออฟไลน์'],
 intro:['Check files and sound separately. Downloading camera files does not start the camera. Browser storage can be cleared or evicted; test a reload without internet before relying on offline use.','分别检查文件和声音。下载摄像头文件不会启动摄像头。浏览器存储可能被清除；依赖离线功能前，请断网后重新加载测试。','फ़ाइलें और आवाज़ अलग जाँचें। कैमरा फ़ाइलें डाउनलोड करने से कैमरा चालू नहीं होता। ब्राउज़र डेटा हट सकता है; ऑफ़लाइन उपयोग से पहले बिना इंटरनेट पेज दोबारा खोलकर जाँचें।','Comprueba archivos y sonido por separado. Descargar archivos no enciende la cámara. El navegador puede borrar datos; prueba recargar sin internet antes de depender del uso sin conexión.','تحقق من الملفات والصوت بشكل منفصل. تنزيل الملفات لا يشغل الكاميرا. قد يمسح المتصفح البيانات؛ جرّب إعادة التحميل دون إنترنت قبل الاعتماد عليه.','ตรวจไฟล์และเสียงแยกกัน การดาวน์โหลดไม่เปิดกล้อง ข้อมูลเบราว์เซอร์อาจถูกลบ ควรลองโหลดใหม่โดยปิดอินเทอร์เน็ตก่อนใช้งานออฟไลน์จริง'],
 board:['Communication board','沟通板','संचार बोर्ड','Tablero de comunicación','لوحة التواصل','กระดานสื่อสาร'],
 hand:['Hand pointer files','手部指针文件','हाथ पॉइंटर की फ़ाइलें','Archivos del puntero de mano','ملفات مؤشر اليد','ไฟล์ตัวชี้มือ'],
 eye:['Eye control files','眼控文件','आँख नियंत्रण की फ़ाइलें','Archivos de control ocular','ملفات التحكم بالعين','ไฟล์ควบคุมด้วยตา'],
 ready:['Files verified on this device','已验证此设备上的文件','इस डिवाइस पर फ़ाइलें सत्यापित','Archivos verificados en este dispositivo','تم التحقق من الملفات على هذا الجهاز','ตรวจสอบไฟล์ในอุปกรณ์แล้ว'],
 missing:['Still to download','仍需下载','अभी डाउनलोड होना बाकी','Pendiente de descargar','متبقي للتنزيل','ยังต้องดาวน์โหลด'],
 download:['Download missing files','下载缺失文件','बाकी फ़ाइलें डाउनलोड करें','Descargar archivos pendientes','تنزيل الملفات الناقصة','ดาวน์โหลดไฟล์ที่ขาด'],
 checking:['Checking…','正在检查…','जाँच जारी…','Comprobando…','جارٍ التحقق…','กำลังตรวจสอบ…'],
 cancel:['Cancel download','取消下载','डाउनलोड रद्द करें','Cancelar descarga','إلغاء التنزيل','ยกเลิกดาวน์โหลด'],
 refresh:['Check again','重新检查','दोबारा जाँचें','Comprobar otra vez','تحقق مجدداً','ตรวจอีกครั้ง'],
 voice:['Chosen voice','所选语音','चुनी हुई आवाज़','Voz elegida','الصوت المختار','เสียงที่เลือก'],
 local:['Local voice listed; sound not checked','已列出本地语音，尚未检查声音','स्थानीय आवाज़ उपलब्ध; ध्वनि नहीं जाँची','Voz local disponible; sonido sin comprobar','صوت محلي متاح؛ لم يُفحص الصوت','มีเสียงในเครื่อง ยังไม่ได้ทดสอบเสียง'],
 online:['Only an online voice is available','仅有在线语音','केवल ऑनलाइन आवाज़ उपलब्ध','Solo hay una voz en línea','يتوفر صوت عبر الإنترنت فقط','มีเฉพาะเสียงออนไลน์'],
 absent:['No matching voice is available','没有匹配语音','मिलती आवाज़ उपलब्ध नहीं','No hay una voz compatible','لا يوجد صوت مطابق','ไม่มีเสียงตรงกับภาษา'],
 play:['Play voice test','播放语音测试','आवाज़ जाँचें','Probar voz','اختبار الصوت','ทดสอบเสียง'],
 heard:['I heard it clearly','我听清楚了','मुझे साफ़ सुनाई दिया','Lo oí claramente','سمعته بوضوح','ได้ยินชัดเจน'],
 confirmed:['You confirmed hearing the test in this session','您已确认本次听到测试声音','आपने इस सत्र में आवाज़ सुनने की पुष्टि की','Confirmaste oír la prueba en esta sesión','أكدت سماع الاختبار في هذه الجلسة','คุณยืนยันว่าได้ยินเสียงทดสอบในครั้งนี้'],
 noSound:['No sound / try again','没声音 / 重试','आवाज़ नहीं / फिर जाँचें','Sin sonido / reintentar','لا صوت / حاول مجدداً','ไม่ได้ยิน / ลองใหม่'],
 off:['Speech is turned off in settings','设置中已关闭语音','सेटिंग में आवाज़ बंद है','La voz está desactivada','الصوت معطل في الإعدادات','ปิดเสียงพูดในการตั้งค่า'],
 reload:['Reload once while online to finish offline setup','联网时重新加载一次以完成离线设置','ऑफ़लाइन सेटअप पूरा करने के लिए ऑनलाइन एक बार रीलोड करें','Recarga con internet para terminar la preparación','أعد التحميل أثناء الاتصال لإكمال الإعداد','โหลดใหม่ขณะออนไลน์เพื่อเตรียมออฟไลน์ให้เสร็จ'],
 close:['Done','完成','हो गया','Listo','تم','เสร็จ'],
};
export const offlineText=(key,lang='en')=>labels[key]?.[langs.indexOf(lang)]||labels[key]?.[0]||key;
export function mountOffline(root,{settings,onClose,onTest,onStop,onTransition}){
 const t=k=>offlineText(k,settings.language);let disposed=false,controller=null,plan=null,statuses={},heard=false,played=false,busy=false;
 const button=(id,label,fn)=>{const b=document.createElement('button');b.id=id;b.className='secondary-button';b.dataset.access='';b.textContent=label;b.onclick=()=>fn(b);return b;};
 root.innerHTML='<p class="intro"></p><div id="offline-details"></div><section id="offline-voice"></section><p id="offline-progress" role="status"></p><div id="offline-actions" class="backup-row"></div>';
 root.querySelector('.intro').textContent=t('intro');const progress=root.querySelector('#offline-progress');
 const actions=root.querySelector('#offline-actions');const refresh=button('offline-refresh',t('refresh'),()=>check()),cancel=button('offline-cancel',t('cancel'),()=>controller?.abort());cancel.hidden=true;actions.append(refresh,cancel,button('offline-done',t('close'),onClose));
 function voice(){if(disposed)return;const lang=settings.speechLanguage&&settings.speechLanguage!=='auto'?settings.speechLanguage:settings.language,voices=window.speechSynthesis?.getVoices()||[],matches=voices.filter(v=>v.lang.toLowerCase().startsWith(lang)),chosen=matches.find(v=>v.localService)||matches[0],box=root.querySelector('#offline-voice');box.replaceChildren();const h=document.createElement('h3');h.textContent=t('voice');const p=document.createElement('p');p.id='offline-voice-status';p.textContent=!settings.voice?t('off'):heard?t('confirmed'):t(chosen?chosen.localService?'local':'online':'absent');if(chosen)p.textContent+=` · ${chosen.name||chosen.lang}`;box.append(h,p);const play=button('offline-play',t('play'),b=>{onTransition(b);heard=false;played=!!onTest();voice();}),yes=button('offline-heard',t('heard'),b=>{onTransition(b);heard=true;voice();}),no=button('offline-no-sound',t('noSound'),b=>{onTransition(b);onStop();heard=false;played=false;voice();});play.disabled=!settings.voice||!chosen||(!navigator.onLine&&!chosen.localService);yes.disabled=!played;box.append(play,yes,no);}
 function cards(){if(disposed)return;const box=root.querySelector('#offline-details');box.replaceChildren();for(const key of ['board','hand','eye']){const s=statuses[key];if(!s)continue;const card=document.createElement('section');card.className='offline-card';const h=document.createElement('h3');h.textContent=t(key);const p=document.createElement('p');p.id='offline-state-'+key;p.textContent=t(s.missing.length?'missing':'ready')+` · ${formatBytes(s.missing.length?s.missingBytes:s.total)}`;card.append(h,p);{const b=button('offline-download-'+key,t('download'),b=>{onTransition(b);download(key);});b.disabled=busy||!s.missing.length;card.append(b);}box.append(card);}}
 async function inspect(){for(const key of ['board','hand','eye'])statuses[key]=await inspectAssets(await caches.open(key==='board'?plan.manifest.boardCache:plan.manifest.trackingCache),plan[key]);cards();}
 async function check(){if(busy||disposed)return;busy=true;refresh.disabled=true;progress.textContent=t('checking');try{if(!('caches' in window)||!navigator.serviceWorker?.controller)throw Error(t('reload'));const response=await fetch(assetPath('/offline-manifest.json'));const raw=await response.arrayBuffer();const manifest=JSON.parse(new TextDecoder().decode(raw));const digest=await crypto.subtle.digest('SHA-256',raw);const manifestAsset={url:assetPath('/offline-manifest.json'),bytes:raw.byteLength,sha256:Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('')};if(manifest.version!==1)throw Error(t('reload'));const script=document.querySelector('script[type=module][src]');if(script&&!manifest.board.some(a=>a.url===new URL(script.src).pathname))throw Error(t('reload'));
   const {FilesetResolver}=await import('@mediapipe/tasks-vision'),runtime=await FilesetResolver.forVisionTasks(assetPath('/tracking'));const paths=[runtime.wasmLoaderPath,runtime.wasmBinaryPath,assetPath('/tracking/LICENSE')];const shared=paths.map(url=>{const a=manifest.tracking.find(a=>a.url===url);if(!a)throw Error(t('reload'));return a;});plan={manifest,board:[...manifest.board,manifestAsset],hand:[...shared,manifest.tracking.find(a=>a.url.endsWith('/hand_landmarker.task'))],eye:[...shared,manifest.tracking.find(a=>a.url.endsWith('/face_landmarker.task'))]};await inspect();if(!disposed)progress.textContent='';
  }catch(error){if(!disposed)progress.textContent=error.message;}finally{busy=false;if(!disposed){refresh.disabled=false;cards();voice();}}}
 async function download(key){if(busy||!plan)return;busy=true;refresh.disabled=true;cancel.hidden=false;controller=new AbortController();cards();try{await prepareAssets(await caches.open(key==='board'?plan.manifest.boardCache:plan.manifest.trackingCache),plan[key],{signal:controller.signal,onProgress:(n,total)=>{if(!disposed)progress.textContent=`${t(key)} · ${formatBytes(n)} / ${formatBytes(total)}`;}});if(!disposed)progress.textContent=t('ready');}catch(error){if(!disposed)progress.textContent=error.name==='AbortError'?t('cancel'):error.message;}finally{busy=false;controller=null;if(!disposed){cancel.hidden=true;refresh.disabled=false;await inspect();}}}
 window.speechSynthesis?.addEventListener('voiceschanged',voice);voice();check();
 return {dispose(){disposed=true;controller?.abort();window.speechSynthesis?.removeEventListener?.('voiceschanged',voice);onStop();}};
}
