import {languages} from './languages.js';
import {exactTranslation} from './partner.js';
import {MessageDraft,mountComposer} from './composer.js';
import {mountSymbolPicker,validPhraseSymbol,symbolText} from './phrase-symbols.js';
import {preparePhrasePhoto,validPhrasePhoto,photoText} from './phrase-photo.js';
export function editPhrase(original,values,source){if(!languages.some(l=>l.id===source))throw Error('Choose a supported original language.');const translations=Object.fromEntries(languages.map(l=>[l.id,typeof values[l.id]==='string'?Array.from(values[l.id].trim()).slice(0,500).join(''):'']).filter(([,v])=>v));if(!translations[source])throw Error('Enter text in the original language before saving.');return {...original,en:translations.en||translations[source],th:translations.th||'',sourceLanguage:source,translations};}
const labels={
 moreLanguages:['Add translations','添加翻译','अनुवाद जोड़ें','Añadir traducciones','إضافة ترجمات','เพิ่มคำแปล'],
 fewerLanguages:['Hide unused languages','隐藏未使用的语言','खाली भाषाएँ छिपाएँ','Ocultar idiomas vacíos','إخفاء اللغات الفارغة','ซ่อนภาษาที่ยังไม่ได้ใช้'],
 create:['Add a personal phrase','添加个人短语','निजी वाक्य जोड़ें','Añadir una frase personal','إضافة عبارة شخصية','เพิ่มข้อความส่วนตัว'],
 createIntro:['Choose the original language and write your message. Large buttons can enter text without a keyboard. Save when ready; translations are optional.','选择原始语言并编写消息。大按钮可用于无键盘输入。准备好后保存；翻译可选。','मूल भाषा चुनें और संदेश लिखें। बड़े बटनों से बिना कीबोर्ड लिख सकते हैं। तैयार होने पर सहेजें; अनुवाद वैकल्पिक हैं।','Elige el idioma original y escribe tu mensaje. Los botones grandes permiten escribir sin teclado. Guarda cuando esté listo; las traducciones son opcionales.','اختر اللغة الأصلية واكتب رسالتك. تتيح الأزرار الكبيرة إدخال النص دون لوحة مفاتيح. احفظ عندما تكون جاهزاً؛ الترجمات اختيارية.','เลือกภาษาต้นฉบับและเขียนข้อความ ใช้ปุ่มใหญ่พิมพ์โดยไม่ต้องใช้แป้นพิมพ์ บันทึกเมื่อพร้อม คำแปลเป็นตัวเลือก'],
 createSave:['Save phrase','保存短语','वाक्य सहेजें','Guardar frase','حفظ العبارة','บันทึกข้อความ'],
 largeEdit:['Edit with large buttons','使用大按钮编辑','बड़े बटनों से बदलें','Editar con botones grandes','التعديل بأزرار كبيرة','แก้ไขด้วยปุ่มใหญ่'],
 title:['Edit personal phrase','编辑个人短语','निजी वाक्य बदलें','Editar frase personal','تعديل عبارة شخصية','แก้ไขข้อความส่วนตัว'],
 intro:['Edit a draft, preview the translations, then save. The phrase stays in its current positions. Recordings only play when their text still matches.','编辑草稿，预览翻译，然后保存。短语保持当前位置。只有原文仍匹配时才播放录音。','मसौदा बदलें, अनुवाद देखें, फिर सहेजें। वाक्य अपनी जगह रहता है। रिकॉर्डिंग तभी चलेगी जब उसका पाठ अब भी मेल खाता हो।','Edita el borrador, revisa las traducciones y guarda. La frase conserva sus posiciones. Las grabaciones solo se usan si el texto sigue coincidiendo.','عدّل المسودة وراجع الترجمات ثم احفظ. تبقى العبارة في مواضعها. لا تُستخدم التسجيلات إلا إذا ظل النص مطابقاً.','แก้ไขร่าง ตรวจคำแปล แล้วบันทึก ตำแหน่งข้อความคงเดิม เสียงบันทึกจะใช้ได้เมื่อข้อความยังตรงกัน'],
 source:['Original language (required text)','原始语言（必须填写文本）','मूल भाषा (पाठ ज़रूरी)','Idioma original (texto obligatorio)','اللغة الأصلية (النص مطلوب)','ภาษาต้นฉบับ (ต้องมีข้อความ)'],
 preview:['Preview draft','预览草稿','मसौदा देखें','Ver borrador','معاينة المسودة','ดูร่าง'],
 reviewed:['I reviewed the translations I want to keep','我已检查要保留的翻译','मैंने रखे जाने वाले अनुवाद जाँच लिए हैं','He revisado las traducciones que conservaré','راجعت الترجمات التي أريد الاحتفاظ بها','ฉันตรวจคำแปลที่จะเก็บไว้แล้ว'],
 hint:['Translations are not updated automatically. Review them or clear translations that no longer match.','翻译不会自动更新。请检查或清除不再匹配的翻译。','अनुवाद अपने आप नहीं बदलते। उन्हें जाँचें या बेमेल अनुवाद हटाएँ।','Las traducciones no cambian automáticamente. Revísalas o borra las que ya no correspondan.','لا تُحدّث الترجمات تلقائياً. راجعها أو امسح ما لم يعد مطابقاً.','คำแปลไม่เปลี่ยนอัตโนมัติ ตรวจหรือล้างคำแปลที่ไม่ตรงแล้ว'],
 save:['Save changes','保存更改','बदलाव सहेजें','Guardar cambios','حفظ التغييرات','บันทึกการเปลี่ยนแปลง'],
 cancel:['Discard edits','放弃修改','बदलाव छोड़ें','Descartar cambios','تجاهل التعديلات','ยกเลิกการแก้ไข'],
 remove:['Remove phrase','删除短语','वाक्य हटाएँ','Eliminar frase','حذف العبارة','ลบข้อความ'],
 removeHint:['Remove this phrase from My phrases? Its pack positions become empty. Saved recordings are kept but will not play unless a matching phrase is restored.','从我的短语中删除此短语？其短语组位置将留空。录音保留，但只有恢复匹配短语后才会播放。','यह वाक्य मेरे वाक्यों से हटाएँ? इसके समूह स्थान खाली रहेंगे। रिकॉर्डिंग रहेंगी, पर मिलते वाक्य को वापस लाने पर ही चलेंगी।','¿Eliminar esta frase? Sus posiciones quedarán vacías. Se conservan las grabaciones, pero solo se usarán si se restaura una frase coincidente.','هل تريد حذف العبارة؟ ستبقى مواضعها فارغة. تُحفظ التسجيلات ولن تعمل إلا عند استعادة عبارة مطابقة.','ลบข้อความนี้หรือไม่? ช่องในชุดข้อความจะว่าง เสียงยังเก็บไว้แต่จะใช้ได้เมื่อกู้ข้อความที่ตรงกัน'],
 keep:['Keep phrase','保留短语','वाक्य रखें','Conservar frase','الاحتفاظ بالعبارة','เก็บข้อความไว้'],
};
export const phraseEditText=(key,lang='en')=>labels[key]?.[languages.findIndex(l=>l.id===lang)]||labels[key]?.[0]||key;
export function mountPhraseEditor(root,{phrase,language,onSave,onCancel,onTransition,phrases=[],creating=false,icons={}}){
 let chosenSymbol=validPhraseSymbol(phrase.icon);
 let photo=validPhrasePhoto(phrase.photo),photoRequest=0,photoBusy=false;
 const t=k=>phraseEditText(k,language),values=Object.fromEntries(languages.map(l=>[l.id,exactTranslation(phrase,l.id)||'']));let source=phrase.sourceLanguage||'en',reviewed=false,previewing=false,translationsOpen=!creating;
 const button=(id,label,fn)=>{const b=document.createElement('button');b.id=id;b.className='secondary-button';b.dataset.access='';b.textContent=label;b.onclick=()=>fn(b);return b;};
 function render(){
 photoRequest++;photoBusy=false;
 root.replaceChildren();const intro=document.createElement('p');intro.className='intro';intro.textContent=t(creating?'createIntro':'intro');root.append(intro);const label=document.createElement('label');label.htmlFor='edit-source';label.textContent=t('source');const select=document.createElement('select');select.id='edit-source';for(const lang of languages){const option=document.createElement('option');option.value=lang.id;option.textContent=lang.name;select.append(option);}select.value=source;label.append(select);root.append(label);
 const sourceButtons=document.createElement('div');sourceButtons.className='language-choices';for(const lang of languages){const b=button('edit-source-'+lang.id,lang.name,b=>{onTransition(b);source=lang.id;select.value=source;reviewed=false;update();});b.lang=lang.id;b.dataset.sourceLanguage=lang.id;sourceButtons.append(b);}root.append(sourceButtons);
 root.append(button('edit-symbol',`${symbolText('title',language)} · ${symbolText(chosenSymbol,language)}`,b=>{onTransition(b);const returnToEditor=()=>{render();root.querySelector('#edit-symbol').focus({preventScroll:true});root.querySelector('#edit-symbol').scrollIntoView({block:'nearest'});};mountSymbolPicker(root,{icons,language,current:chosenSymbol,onTransition,onChoose:key=>{chosenSymbol=key;returnToEditor();},onClose:returnToEditor});}));
 const fields=document.createElement('div');fields.className='phrase-edit-fields';root.append(fields);for(const lang of languages){const l=document.createElement('label');l.htmlFor='edit-text-'+lang.id;l.textContent=lang.name;const field=document.createElement('textarea');field.id=l.htmlFor;field.lang=lang.id;field.dir='auto';field.rows=2;field.maxLength=500;field.value=values[lang.id];field.oninput=()=>{values[lang.id]=field.value;reviewed=false;update();};l.append(field);fields.append(l);}
 for(const lang of languages){const field=root.querySelector('#edit-text-'+lang.id);field.parentElement.after(button('edit-large-'+lang.id,`${t('largeEdit')} · ${lang.name}`,b=>{onTransition(b);const draft=new MessageDraft(lang.id);draft.set(values[lang.id]);draft.history=[];mountComposer(root,{draft,phrases:phrases.filter(p=>exactTranslation(p,lang.id)),uiLanguage:language,onTransition,onApply:text=>{values[lang.id]=text;reviewed=false;render();root.querySelector('#edit-text-'+lang.id).scrollIntoView({block:'center'});},onClose:()=>{render();root.querySelector('#edit-text-'+lang.id).scrollIntoView({block:'center'});}});root.closest('dialog').scrollTop=0;}));}
 const more=button('edit-translations',t('moreLanguages'),b=>{onTransition(b);translationsOpen=!translationsOpen;update();});more.setAttribute('aria-controls','phrase-language-fields');fields.id='phrase-language-fields';root.append(more);
 const photoSection=document.createElement('section');photoSection.className='phrase-photo-editor';const photoLabel=document.createElement('label');photoLabel.textContent=photoText('choose',language);const photoInput=document.createElement('input');photoInput.id='edit-photo-file';photoInput.type='file';photoInput.accept='image/jpeg,image/png,image/webp';photoLabel.append(photoInput);const photoNote=document.createElement('p');photoNote.className='note';photoNote.textContent=photoText('note',language);const photoStatus=document.createElement('p');photoStatus.id='edit-photo-status';photoStatus.setAttribute('role','status');photoSection.append(photoLabel,photoNote,photoStatus);if(photo){const img=document.createElement('img');img.id='edit-photo-preview';img.src=photo;img.alt='';photoSection.append(img,button('edit-photo-remove',photoText('remove',language),b=>{onTransition(b);photo=null;render();}));}const cancelPhoto=button('edit-photo-cancel',photoText('cancel',language),b=>{onTransition(b);photoRequest++;photoBusy=false;photoInput.value='';photoStatus.textContent='';update();});cancelPhoto.hidden=true;photoSection.append(cancelPhoto);root.append(photoSection);
 photoInput.onchange=async()=>{const file=photoInput.files[0];if(!file)return;const request=++photoRequest;photoBusy=true;photoStatus.textContent=photoText('working',language);update();try{const prepared=await preparePhrasePhoto(file);if(request!==photoRequest||!photoInput.isConnected)return;photo=prepared;render();}catch{if(request===photoRequest&&photoInput.isConnected)photoStatus.textContent=photoText('failed',language);}finally{if(request===photoRequest&&photoInput.isConnected){photoBusy=false;update();}}};
 function showFields(){
  more.textContent=t(translationsOpen?'fewerLanguages':'moreLanguages');more.setAttribute('aria-expanded',String(translationsOpen));
  for(const lang of languages){const field=root.querySelector('#edit-text-'+lang.id),entry=root.querySelector('#edit-large-'+lang.id);const hidden=!translationsOpen&&lang.id!==source&&!values[lang.id].trim();field.parentElement.hidden=hidden;entry.hidden=hidden;}
  const original=root.querySelector('#edit-text-'+source);if(fields.firstElementChild!==original.parentElement)fields.prepend(original.parentElement,root.querySelector('#edit-large-'+source));
 }
 const hint=document.createElement('p');hint.className='note';hint.textContent=t('hint');root.append(hint);const preview=document.createElement('div');preview.id='phrase-edit-preview';root.append(preview);const status=document.createElement('p');status.id='phrase-edit-status';status.setAttribute('role','status');root.append(status);
 const actions=document.createElement('div');actions.className='compose-actions';root.append(actions);const review=button('edit-reviewed',t('reviewed'),b=>{onTransition(b);reviewed=!reviewed;update();}),save=button('edit-save',t(creating?'createSave':'save'),b=>{onTransition(b);try{const next=editPhrase({...phrase,icon:chosenSymbol,photo},values,source);onSave(next);}catch(error){status.textContent=error.message;}});actions.append(button('edit-preview',t('preview'),b=>{onTransition(b);previewing=true;update();preview.scrollIntoView({block:'nearest'});}),review,save,button('edit-cancel',t('cancel'),b=>{onTransition(b);onCancel();}));select.onchange=()=>{source=select.value;reviewed=false;update();};
 function update(){cancelPhoto.hidden=!photoBusy;showFields();for(const b of sourceButtons.children)b.setAttribute('aria-pressed',String(b.dataset.sourceLanguage===source));for(const lang of languages)root.querySelector('#edit-text-'+lang.id).required=lang.id===source;const multiple=Object.values(values).filter(v=>v.trim()).length>1;review.hidden=!multiple;review.setAttribute('aria-pressed',String(reviewed));save.disabled=photoBusy||!values[source]?.trim()||(multiple&&!reviewed);preview.replaceChildren();if(previewing)for(const lang of languages)if(values[lang.id].trim()){const section=document.createElement('section');section.className='partner-message';const title=document.createElement('strong');title.textContent=lang.name;const text=document.createElement('p');text.lang=lang.id;text.dir='auto';text.textContent=values[lang.id].trim();section.append(title,text);preview.append(section);}}
 update();for(const b of sourceButtons.children)b.setAttribute('aria-pressed',String(b.dataset.sourceLanguage===source));
 }
 render();
}






