export const recordingKey=(phrase,language)=>JSON.stringify([phrase,language]);
const MAX_CLIP=2_000_000,MAX_TOTAL=10_000_000;
const request=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
const complete=tx=>new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Recording transaction cancelled.'));});
export class RecordingLibrary{
 constructor(){this.person=null;this.items=new Map();this.generation=0;}
 async db(){if(!this.opening)this.opening=new Promise((resolve,reject)=>{const req=indexedDB.open('reach-recordings',1);req.onupgradeneeded=()=>{const store=req.result.createObjectStore('clips',{keyPath:'id'});store.createIndex('person','person');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return this.opening;}
 async load(person){const generation=++this.generation;this.person=person;this.items=new Map();const db=await this.db(),clips=await request(db.transaction('clips').objectStore('clips').index('person').getAll(person));if(generation!==this.generation)return;this.items=new Map(clips.map(c=>[recordingKey(c.phrase,c.language),c]));}
 get(phrase,language,text){const clip=this.items.get(recordingKey(phrase,language));return clip?.text===text?clip:null;}
 async all(){const person=this.person,db=await this.db();return request(db.transaction('clips').objectStore('clips').index('person').getAll(person));}
 async importClips(clips,{person,replace=false}){
  if(person!==this.person)throw Error('The current person changed. Reopen the recording backup.');
  const db=await this.db(),tx=db.transaction('clips','readwrite'),done=complete(tx),store=tx.objectStore('clips'),existing=await request(store.index('person').getAll(person));
  const merged=new Map(existing.map(c=>[recordingKey(c.phrase,c.language),c])),added=[];
  for(const clip of clips){const key=recordingKey(clip.phrase,clip.language);if(!replace&&merged.has(key))continue;const entry={...clip,person,id:JSON.stringify([person,clip.phrase,clip.language])};merged.set(key,entry);added.push(entry);}
  if(person!==this.person||merged.size>100||[...merged.values()].reduce((n,c)=>n+c.blob.size,0)>MAX_TOTAL){tx.abort();await done.catch(()=>{});throw Error('Profile changed or recording limit exceeded (100 clips / 10 MB). Nothing was imported.');}
  try{for(const clip of added)store.put(clip);await done;}catch(error){try{tx.abort();}catch{}await done.catch(()=>{});throw error;}if(this.person===person)this.items=merged;return added.length;
 }
 async save({phrase,language,text,blob}){if(!this.person||!phrase||!text||!blob?.size||blob.size>MAX_CLIP||!blob.type.startsWith('audio/'))throw Error('Record up to 30 seconds of audio (maximum 2 MB).');const person=this.person,db=await this.db(),tx=db.transaction('clips','readwrite'),done=complete(tx),store=tx.objectStore('clips'),clips=await request(store.index('person').getAll(person)),id=JSON.stringify([person,phrase,language]);if(clips.filter(c=>c.id!==id).reduce((n,c)=>n+c.blob.size,0)+blob.size>MAX_TOTAL||clips.filter(c=>c.id!==id).length>=100){tx.abort();await done.catch(()=>{});throw Error('Recording storage is full for this person (100 clips / 10 MB). Download and remove unused clips.');}const clip={id,person,phrase,language,text,blob};store.put(clip);await done;if(this.person===person)this.items.set(recordingKey(phrase,language),clip);}
 async remove(phrase,language){const person=this.person,db=await this.db(),tx=db.transaction('clips','readwrite'),done=complete(tx);tx.objectStore('clips').delete(JSON.stringify([person,phrase,language]));await done;if(this.person===person)this.items.delete(recordingKey(phrase,language));}
 async removePerson(person){const db=await this.db(),tx=db.transaction('clips','readwrite'),done=complete(tx),index=tx.objectStore('clips').index('person'),req=index.openCursor(IDBKeyRange.only(person));req.onsuccess=()=>{const cursor=req.result;if(cursor){cursor.delete();cursor.continue();}};await done;}
}
export class RecordedOutput{
 stop(){this.generation=(this.generation||0)+1;if(this.audio){this.audio.pause();this.audio.removeAttribute('src');this.audio.load();this.audio=null;}if(this.url){URL.revokeObjectURL(this.url);this.url=null;}}
 play(blob,onError=()=>{}){this.stop();const generation=this.generation;this.url=URL.createObjectURL(blob);const audio=this.audio=new Audio(this.url);audio.onended=()=>{if(this.audio===audio)this.stop();};audio.play().catch(()=>{if(generation===this.generation){this.stop();onError();}});}
}
const languages=['en','zh','hi','es','ar','th'];
const labels={
 stopPlayback:['Stop playback','停止播放','आवाज़ रोकें','Detener reproducción','إيقاف التشغيل','หยุดเล่นเสียง'],
 title:['Recorded speech','录制语音','रिकॉर्ड की गई आवाज़','Voz grabada','الكلام المسجل','เสียงที่บันทึก'],
 intro:['Record the exact message shown, in the selected language. Preview it before saving. Saved recordings play instead of the device voice for that message. Microphone audio stays on this device. Setup exports do not include audio: download each clip to keep a copy.','请用所选语言录制显示的原文，保存前试听。已保存的录音将替代设备语音。音频保留在此设备上。设置导出不包含音频，请分别下载备份。','दिखाया संदेश चुनी भाषा में रिकॉर्ड करें। सहेजने से पहले सुनें। यह रिकॉर्डिंग उस संदेश की डिवाइस आवाज़ की जगह चलेगी। ऑडियो यहीं रहता है। सेटअप निर्यात में ऑडियो नहीं है; हर क्लिप डाउनलोड करके रखें।','Graba el mensaje exacto en el idioma elegido y escúchalo antes de guardarlo. Sustituirá la voz del dispositivo para ese mensaje. El audio queda aquí. No se incluye al exportar ajustes; descarga cada grabación para conservarla.','سجّل النص المعروض باللغة المختارة واستمع إليه قبل الحفظ. سيحل التسجيل محل صوت الجهاز لهذه الرسالة. يبقى الصوت على هذا الجهاز ولا يُضمّن في تصدير الإعدادات؛ نزّل كل مقطع للاحتفاظ بنسخة.','บันทึกข้อความที่แสดงตรงตามภาษา แล้วฟังก่อนบันทึก เสียงนี้จะใช้แทนเสียงอุปกรณ์สำหรับข้อความนั้น เสียงอยู่ในเครื่องและไม่รวมในการส่งออกการตั้งค่า ดาวน์โหลดแต่ละคลิปเพื่อเก็บสำเนา'],
 start:['Record message','录制消息','संदेश रिकॉर्ड करें','Grabar mensaje','تسجيل الرسالة','อัดข้อความ'],stop:['Stop recording','停止录制','रिकॉर्डिंग रोकें','Detener grabación','إيقاف التسجيل','หยุดอัด'],preview:['Preview recording','试听录音','रिकॉर्डिंग सुनें','Escuchar grabación','معاينة التسجيل','ฟังเสียงที่อัด'],save:['Use this recording','使用此录音','यह रिकॉर्डिंग इस्तेमाल करें','Usar esta grabación','استخدام هذا التسجيل','ใช้เสียงนี้'],remove:['Remove saved recording','删除已保存录音','सहेजी रिकॉर्डिंग हटाएँ','Eliminar grabación guardada','حذف التسجيل المحفوظ','ลบเสียงที่บันทึก'],download:['Download saved clip','下载已保存录音','सहेजी क्लिप डाउनलोड करें','Descargar grabación','تنزيل المقطع المحفوظ','ดาวน์โหลดคลิปที่บันทึก'],saved:['Recording saved on this device','录音已保存在此设备','रिकॉर्डिंग इस डिवाइस पर सहेजी गई','Grabación guardada en este dispositivo','تم حفظ التسجيل على هذا الجهاز','บันทึกเสียงไว้ในอุปกรณ์แล้ว'],playing:['Saved recording · works offline','已保存录音 · 可离线播放','सहेजी रिकॉर्डिंग · ऑफ़लाइन उपलब्ध','Grabación guardada · sin conexión','تسجيل محفوظ · يعمل دون اتصال','เสียงที่บันทึก · ใช้ออฟไลน์ได้'],back:['Back','返回','वापस','Volver','رجوع','กลับ'],next:['Next','下一页','अगला','Siguiente','التالي','ถัดไป'],previous:['Previous','上一页','पिछला','Anterior','السابق','ก่อนหน้า'],done:['Done','完成','हो गया','Listo','تم','เสร็จ'],
};
export const recordingText=(key,lang='en')=>labels[key]?.[languages.indexOf(lang)]||labels[key]?.[0]||key;
export function mountRecordings(root,{library,phrases,language,uiLanguage=language,onClose,onTransition,onStop,onBackup,backupLabel}){
 const t=k=>recordingText(k,uiLanguage),previewOutput=new RecordedOutput();let page=0,selected=null,stream=null,recorder=null,timer=null,draft=null,previewed=false,disposed=false,requesting=false,captureGeneration=0;
 const button=(id,label,fn)=>{const b=document.createElement('button');b.id=id;b.className='secondary-button';b.dataset.access='';b.textContent=label;b.onclick=()=>fn(b);return b;};
 const status=text=>{if(!disposed)root.querySelector('#recording-status').textContent=text;};
 const halt=()=>{clearTimeout(timer);if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());stream=null;};
 function render(){if(disposed)return;root.replaceChildren();const intro=document.createElement('p');intro.className='intro';intro.textContent=t('intro');root.append(intro);const message=document.createElement('p');message.id='recording-status';message.setAttribute('role','status');root.append(message);
  if(!selected){if(onBackup)root.append(button('record-backup',backupLabel,b=>{onTransition(b);onBackup();}));const grid=document.createElement('div');grid.className='care-grid';root.append(grid);phrases.slice(page*4,page*4+4).forEach(p=>{const b=button('record-phrase-'+p.id,p.text,b=>{onTransition(b);selected=p;draft=null;previewed=false;render();});grid.append(b);});const nav=document.createElement('div');nav.className='backup-row';const prev=button('record-prev',t('previous'),b=>{onTransition(b);page--;render();}),next=button('record-next',t('next'),b=>{onTransition(b);page++;render();});prev.disabled=page===0;next.disabled=(page+1)*4>=phrases.length;nav.append(prev,next);root.append(nav);
  }else{const p=document.createElement('p');p.className='care-review';p.lang=language;p.dir='auto';p.textContent=selected.text;root.append(p);const current=library.get(selected.id,language,selected.text),actions=document.createElement('div');actions.className='compose-actions';root.append(actions);
   const start=button('record-start',t('start'),async b=>{onTransition(b);onStop();previewOutput.stop();draft=null;previewed=false;requesting=true;const generation=++captureGeneration;render();try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Recording is unavailable in this browser.');const acquired=await navigator.mediaDevices.getUserMedia({audio:true,video:false});if(disposed||generation!==captureGeneration){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(type=>MediaRecorder.isTypeSupported(type));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{if(disposed||generation!==captureGeneration)return;draft=new Blob(chunks,{type:recorder.mimeType});recorder=null;render();};recorder.onerror=()=>{halt();status('Recording failed. Please try again.');};recorder.start();timer=setTimeout(halt,30000);requesting=false;render();status('Recording… 30 seconds maximum.');}catch(error){if(disposed||generation!==captureGeneration)return;halt();requesting=false;render();status(error.message);}});start.disabled=requesting||recorder?.state==='recording';const stop=button('record-stop',t('stop'),()=>halt());stop.disabled=recorder?.state!=='recording';
   const preview=button('record-preview',t('preview'),b=>{onTransition(b);onStop();previewOutput.play(draft||current.blob,()=>{previewed=false;render();status('Audio could not play. Check your device sound.');});previewed=true;render();});preview.disabled=(!draft&&!current)||requesting||recorder?.state==='recording';const save=button('record-save',t('save'),async b=>{onTransition(b);try{await library.save({phrase:selected.id,language,text:selected.text,blob:draft});draft=null;previewed=false;render();status(t('saved'));}catch(error){status(error.message);}});save.disabled=!draft||!previewed||requesting||recorder?.state==='recording';actions.append(start,stop,preview,save);
   const remove=button('record-remove',t('remove'),async()=>{try{await library.remove(selected.id,language);previewOutput.stop();render();}catch(error){status(error.message);}});remove.disabled=!current;const download=button('record-download',t('download'),()=>{const url=URL.createObjectURL(current.blob),a=document.createElement('a');a.href=url;a.download=`reach-${selected.id}-${language}.${current.blob.type.includes('mp4')?'m4a':current.blob.type.includes('ogg')?'ogg':'webm'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});download.disabled=!current;actions.append(remove,download);
   actions.append(button('record-playback-stop',t('stopPlayback'),()=>{previewOutput.stop();onStop();}));
   root.append(button('record-back',t('back'),b=>{onTransition(b);captureGeneration++;halt();recorder=null;requesting=false;previewOutput.stop();selected=null;draft=null;previewed=false;render();}));
  }root.append(button('record-done',t('done'),onClose));
 }
 render();return {dispose(){disposed=true;captureGeneration++;halt();previewOutput.stop();}};
}
