import {languages,ui} from './languages.js';
const codes=['en','zh','hi','es','ar','th'];
const labels={
 draftSaved:['Answers are kept in this tab until you apply or cancel. They have not changed your current setup.','答案会保留在此标签页中，直到应用或取消。目前的设置尚未改变。','लागू करने या रद्द करने तक उत्तर इस टैब में रखे जाते हैं। वर्तमान सेटअप नहीं बदला है।','Las respuestas se conservan en esta pestaña hasta aplicar o cancelar. Tu configuración actual no ha cambiado.','تُحفظ الإجابات في علامة التبويب هذه حتى التطبيق أو الإلغاء. لم تتغير إعداداتك الحالية.','คำตอบเก็บไว้ในแท็บนี้จนกว่าจะใช้หรือยกเลิก การตั้งค่าปัจจุบันยังไม่เปลี่ยน'],
 draftUnavailable:['Answers could not be kept for reload. Keep this page open to finish setup.','无法保留答案供重新加载使用。请保持此页面打开以完成设置。','पेज दोबारा लोड करने के लिए उत्तर नहीं रखे जा सके। सेटअप पूरा करने तक पेज खुला रखें।','No se pudieron conservar las respuestas para recargar. Mantén esta página abierta para terminar.','تعذّر حفظ الإجابات لإعادة التحميل. أبقِ الصفحة مفتوحة لإكمال الإعداد.','เก็บคำตอบไว้หลังโหลดใหม่ไม่ได้ เปิดหน้านี้ไว้จนตั้งค่าเสร็จ'],
 saveFailed:['Your setup could not be saved. Your choices are still here. Try again, or keep your current setup.','无法保存设置。您的选择仍在此处。请重试，或保留当前设置。','सेटअप सहेजा नहीं जा सका। आपके विकल्प यहीं हैं। फिर कोशिश करें या वर्तमान सेटअप रखें।','No se pudo guardar la configuración. Tus elecciones siguen aquí. Inténtalo de nuevo o conserva tu configuración actual.','تعذّر حفظ الإعدادات. اختياراتك ما زالت هنا. حاول مجدداً أو احتفظ بإعداداتك الحالية.','บันทึกการตั้งค่าไม่ได้ ตัวเลือกของคุณยังอยู่ที่นี่ ลองอีกครั้งหรือใช้การตั้งค่าเดิม'],
 title:['Find my setup','找到适合我的设置','मेरे लिए सेटअप खोजें','Encontrar mi configuración','العثور على إعداداتي','หาการตั้งค่าที่เหมาะกับฉัน'],
 intro:['A helper can answer these questions with you. Nothing changes until you apply the reviewed setup. Keep the person comfortable and let them choose.','助手可以和您一起回答。确认应用前不会改变设置。请让使用者保持舒适并自行选择。','सहायक आपके साथ उत्तर दे सकता है। समीक्षा के बाद लागू करने तक कुछ नहीं बदलता। व्यक्ति को आराम दें और उन्हें चुनने दें।','Una persona puede ayudarte a responder. Nada cambia hasta aplicar la configuración revisada. Busca comodidad y deja que la persona elija.','يمكن لمساعد الإجابة معك. لا يتغير شيء حتى تطبق الإعدادات بعد مراجعتها. حافظ على راحة الشخص ودعه يختار.','ผู้ช่วยตอบร่วมกับคุณได้ จะยังไม่เปลี่ยนการตั้งค่าจนกว่าจะตรวจและนำไปใช้ ให้ผู้ใช้สบายและเลือกเอง'],
 reading:['How do you prefer messages?','您希望如何理解消息？','संदेश कैसे समझना पसंद करेंगे?','¿Cómo prefieres entender los mensajes?','كيف تفضّل فهم الرسائل؟','ต้องการเข้าใจข้อความอย่างไร'],
 read:['I can read the words','我能阅读文字','मैं शब्द पढ़ सकता/सकती हूँ','Puedo leer las palabras','أستطيع قراءة الكلمات','ฉันอ่านข้อความได้'],
 larger:['Larger words and targets','更大的文字和目标','बड़े शब्द और बटन','Palabras y botones más grandes','كلمات وأهداف أكبر','ข้อความและปุ่มใหญ่ขึ้น'],
 partner:['A partner reads them to me','由伙伴读给我听','साथी मुझे पढ़कर सुनाए','Alguien me los lee','يقرأها لي شريك','ให้คู่สื่อสารอ่านให้ฟัง'],
 unsure:['Not sure yet','尚不确定','अभी पता नहीं','Aún no lo sé','لست متأكداً بعد','ยังไม่แน่ใจ'],
 position:['Where will you use it?','您将在哪里使用？','आप किस स्थिति में इस्तेमाल करेंगे?','¿En qué posición lo usarás?','في أي وضعية ستستخدمه؟','จะใช้ในท่าใด'],
 seated:['Sitting with support','有支撑地坐着','सहारे के साथ बैठकर','Sentado/a con apoyo','جالساً مع دعم','นั่งโดยมีที่รองรับ'],
 reclined:['Reclining or lying down','斜躺或平躺','झुककर या लेटकर','Reclinado/a o tumbado/a','متكئاً أو مستلقياً','เอนหรือนอน'],
 changing:['My position changes often','我的姿势经常改变','मेरी स्थिति अक्सर बदलती है','Cambio de posición a menudo','أغيّر وضعيتي كثيراً','เปลี่ยนท่าบ่อย'],
 input:['How can you select comfortably?','您怎样选择最舒适？','आराम से कैसे चुन सकते हैं?','¿Cómo puedes seleccionar cómodamente?','كيف تختار براحة؟','เลือกด้วยวิธีใดได้สบาย'],
 touch:['Touch or click a large button','触摸或点击大按钮','बड़ा बटन छुएँ या क्लिक करें','Tocar o hacer clic en un botón grande','لمس زر كبير أو النقر عليه','แตะหรือคลิกปุ่มใหญ่'],
 dwell:['Move a pointer, then hold still','移动指针，然后保持不动','पॉइंटर हिलाएँ और स्थिर रखें','Mover el puntero y mantenerlo quieto','تحريك المؤشر ثم تثبيته','เลื่อนตัวชี้แล้วค้างไว้'],
 switch:['Press one key or switch','按一个按键或开关','एक कुंजी या स्विच दबाएँ','Pulsar una tecla o un conmutador','ضغط مفتاح أو مفتاح مساعد واحد','กดปุ่มหรือสวิตช์เดียว'],
 camera:['Try a normal webcam','尝试普通摄像头','सामान्य वेबकैम आज़माएँ','Probar una cámara web normal','تجربة كاميرا ويب عادية','ลองใช้กล้องเว็บแคมทั่วไป'],
 helper:['A helper will select for me','由助手替我选择','सहायक मेरे लिए चुनेगा','Alguien seleccionará por mí','سيختار مساعد نيابة عني','ให้ผู้ช่วยเลือกให้'],
 hand:['Move a finger to point','移动手指来指向','उँगली हिलाकर इशारा करें','Mover un dedo para apuntar','تحريك إصبع للإشارة','ขยับนิ้วเพื่อชี้'],
 motion:['Make one movement, then relax','做一个动作，然后放松','एक हरकत करें, फिर आराम दें','Hacer un movimiento y relajarlo','حركة واحدة ثم استرخاء','ขยับหนึ่งครั้งแล้วผ่อนคลาย'],
 eye:['Look at large targets · experimental','看大目标 · 实验功能','बड़े लक्ष्य देखें · प्रयोगात्मक','Mirar objetivos grandes · experimental','النظر إلى أهداف كبيرة · تجريبي','มองเป้าใหญ่ · ทดลอง'],
 review:['Review before applying','应用前检查','लागू करने से पहले समीक्षा','Revisar antes de aplicar','المراجعة قبل التطبيق','ตรวจสอบก่อนใช้'],
 apply:['Apply and try it','应用并试用','लागू करें और आज़माएँ','Aplicar y probar','التطبيق والتجربة','ใช้แล้วทดลอง'],
 back:['Back','返回','वापस','Volver','رجوع','กลับ'],
 cancel:['Keep my current setup','保留当前设置','वर्तमान सेटअप रखें','Mantener mi configuración','الإبقاء على إعداداتي الحالية','ใช้การตั้งค่าเดิม'],
 cameraHint:['Settle into your usual position before calibrating. Recalibrate after moving the camera or changing position. Camera methods are experimental; the practice trial helps you observe selections, not prove reliability.','校准前先采用常用姿势。移动摄像头或改变姿势后重新校准。摄像头方法是实验性的；练习用于观察选择情况，不能证明可靠性。','कैलिब्रेशन से पहले सामान्य स्थिति में आराम से रहें। कैमरा या स्थिति बदलने पर फिर कैलिब्रेट करें। कैमरा विधियाँ प्रयोगात्मक हैं; अभ्यास चयन देखने के लिए है, विश्वसनीयता साबित करने के लिए नहीं।','Adopta tu posición habitual antes de calibrar. Recalibra al mover la cámara o cambiar de posición. Estos métodos son experimentales; la práctica permite observar selecciones, no demostrar fiabilidad.','اتخذ وضعيتك المعتادة قبل المعايرة وأعدها بعد تحريك الكاميرا أو تغيير الوضعية. طرق الكاميرا تجريبية؛ التدريب يتيح ملاحظة الاختيارات ولا يثبت الموثوقية.','จัดท่าที่ใช้ประจำก่อนปรับเทียบ และปรับใหม่หลังขยับกล้องหรือเปลี่ยนท่า วิธีใช้กล้องยังเป็นการทดลอง การฝึกช่วยสังเกตการเลือกแต่ไม่ยืนยันความแม่นยำ'],
 helperHint:['Agree on the person’s yes/no signal. Read one choice at a time and wait for their response. This board uses words and simple icons; it is not a complete symbol-language system.','先约定使用者的是/否信号。一次读一个选项，等待回答。本板使用文字和简单图标，不是完整的符号语言系统。','व्यक्ति के हाँ/नहीं संकेत पर सहमति करें। एक समय में एक विकल्प पढ़ें और उत्तर का इंतज़ार करें। इस बोर्ड में शब्द और सरल चिह्न हैं; यह पूरा प्रतीक-भाषा तंत्र नहीं है।','Acuerda las señales de sí y no. Lee una opción cada vez y espera la respuesta. El tablero usa palabras e iconos sencillos; no es un sistema completo de lenguaje por símbolos.','اتفق على إشارة نعم ولا، واقرأ خياراً واحداً وانتظر الإجابة. تستخدم اللوحة كلمات وأيقونات بسيطة وليست نظاماً كاملاً للغة الرموز.','ตกลงสัญญาณใช่และไม่ใช่ อ่านทีละตัวเลือกแล้วรอคำตอบ กระดานนี้ใช้คำและไอคอนง่าย ๆ ไม่ใช่ระบบภาษาสัญลักษณ์ที่ครบถ้วน'],
 pointerHint:['If another accessibility tool already moves and clicks the pointer, choose Touch or click to avoid two systems selecting at once.','如果其他辅助工具已移动并点击指针，请选触摸或点击，避免两个系统同时选择。','यदि दूसरा सहायक टूल पॉइंटर हिलाकर क्लिक करता है, दोहरे चयन से बचने के लिए छुएँ या क्लिक करें चुनें।','Si otra herramienta ya mueve y hace clic con el puntero, elige Tocar o hacer clic para evitar selecciones dobles.','إذا كانت أداة أخرى تحرك المؤشر وتنقر به فاختر اللمس أو النقر لتجنب اختيار النظامين معاً.','หากเครื่องมือช่วยอื่นเลื่อนและคลิกตัวชี้อยู่แล้ว ให้เลือกแตะหรือคลิกเพื่อหลีกเลี่ยงการเลือกซ้ำ'],
};
export const guideText=(key,lang='en')=>labels[key]?.[codes.indexOf(lang)]||labels[key]?.[0]||ui(key,lang);
export function guideSettings(current,answers){return {...current,language:answers.language,mode:answers.method==='helper'?'touch':answers.method,simple:answers.reading==='larger'||answers.reading==='partner'||answers.reading==='unsure'?true:current.simple,setupGuide:{reading:answers.reading,position:answers.position,helper:answers.method==='helper'}};}
export function cleanGuideDraft(draft){
 if(!draft||!Number.isInteger(draft.step)||draft.step<0||draft.step>5)return null;
 const a=draft.answers;if(!a||!codes.includes(a.language)||![null,'read','larger','partner','unsure'].includes(a.reading)||![null,'seated','reclined','changing','unsure'].includes(a.position)||![null,'touch','dwell','switch','camera','hand','motion','eye','helper'].includes(a.method))return null;
 if(draft.step>=2&&!a.reading||draft.step>=3&&!a.position||draft.step===4&&!['camera','hand','motion','eye'].includes(a.method)||draft.step===5&&(!a.method||a.method==='camera'))return null;
 return {step:draft.step,answers:{language:a.language,reading:a.reading,position:a.position,method:a.method}};
}
export function mountSetupGuide(root,{settings,onApply,onClose,onTransition,onTitle,draft=null,onDraftChange=()=>undefined}){
 const restored=cleanGuideDraft(draft);const answers=restored?.answers||{language:settings.language,reading:settings.setupGuide?.reading||null,position:settings.setupGuide?.position||null,method:null};let step=restored?.step||0;
 const button=(id,label,fn)=>{const b=document.createElement('button');b.id=id;b.className='profile-choice';b.dataset.access='';b.textContent=label;b.onclick=()=>fn(b);return b;};
 function render(){const t=k=>guideText(k,answers.language);root.replaceChildren();root.lang=answers.language;root.dir=answers.language==='ar'?'rtl':'ltr';onTitle(t('title'));const intro=document.createElement('p');intro.className='intro';intro.textContent=t('intro');root.append(intro);const h=document.createElement('h3');h.id='guide-question';h.textContent=step===0?ui('language',answers.language):t(['','reading','position','input','camera','review'][step]);root.append(h);const grid=document.createElement('div');grid.className='guide-grid';root.append(grid);
  const choose=(b,field,value,next)=>{onTransition(b);answers[field]=value;step=next;render();};
  if(step===0)for(const lang of languages){const b=button('guide-lang-'+lang.id,lang.name,b=>choose(b,'language',lang.id,1));b.lang=lang.id;grid.append(b);}
  if(step===1)for(const v of ['read','larger','partner','unsure'])grid.append(button('guide-reading-'+v,t(v),b=>choose(b,'reading',v,2)));
  if(step===2)for(const v of ['seated','reclined','changing','unsure'])grid.append(button('guide-position-'+v,t(v),b=>choose(b,'position',v,3)));
  if(step===3){for(const v of ['touch','dwell','switch','camera'])grid.append(button('guide-input-'+v,t(v),b=>choose(b,'method',v,v==='camera'?4:5)));root.append(button('guide-input-helper',t('helper'),b=>choose(b,'method','helper',5)));}
  if(step===4)for(const v of ['hand','motion','eye'])grid.append(button('guide-camera-'+v,t(v),b=>choose(b,'method',v,5)));
  if(step===5){const summary=document.createElement('dl');summary.className='practice-results';for(const [label,value]of [[ui('language',answers.language),languages.find(l=>l.id===answers.language).name],[t('reading'),t(answers.reading)],[t('position'),t(answers.position)],[t('input'),t(answers.method)]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;summary.append(dt,dd);}root.append(summary);root.append(button('guide-apply',t('apply'),b=>{onTransition(b);if(onApply(guideSettings(settings,answers))===false){let status=root.querySelector('#guide-save-error');if(!status){status=document.createElement('p');status.id='guide-save-error';status.className='note';status.setAttribute('role','alert');b.after(status);}status.textContent=t('saveFailed');status.scrollIntoView({block:'nearest'});}}));}
  const hint=document.createElement('p');hint.className='note';hint.textContent=step===3?t('pointerHint'):answers.method==='helper'||['partner','unsure'].includes(answers.reading)?t('helperHint'):t('cameraHint');hint.hidden=step<2||(step===5&&!['hand','motion','eye','helper'].includes(answers.method)&&!['partner','unsure'].includes(answers.reading));root.append(hint);
  const persisted=onDraftChange({step,answers:{...answers}});if(persisted!==undefined){const status=document.createElement('p');status.id='guide-draft-status';status.className='note';status.setAttribute('role','status');status.textContent=t(persisted?'draftSaved':'draftUnavailable');root.append(status);}
  const actions=document.createElement('div');actions.className='backup-row';if(step>0)actions.append(button('guide-back',t('back'),b=>{onTransition(b);step=step===5?(['hand','motion','eye'].includes(answers.method)?4:3):step-1;render();}));actions.append(button('guide-cancel',t('cancel'),onClose));root.append(actions);root.closest('dialog').scrollTop=0;h.tabIndex=-1;h.focus({preventScroll:true});
 }
 render();
}
